// Code generated by ent, DO NOT EDIT.

package systempromptruntime

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldLTE(FieldID, id))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldEnabled, v))
}

// ExposeServerPrompt applies equality check predicate on the "expose_server_prompt" field. It's identical to ExposeServerPromptEQ.
func ExposeServerPrompt(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldExposeServerPrompt, v))
}

// CompactEnabled applies equality check predicate on the "compact_enabled" field. It's identical to CompactEnabledEQ.
func CompactEnabled(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldCompactEnabled, v))
}

// ActiveTemplateID applies equality check predicate on the "active_template_id" field. It's identical to ActiveTemplateIDEQ.
func ActiveTemplateID(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldActiveTemplateID, v))
}

// ActiveVersionID applies equality check predicate on the "active_version_id" field. It's identical to ActiveVersionIDEQ.
func ActiveVersionID(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldActiveVersionID, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldRevision, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldUpdatedAt, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldEnabled, v))
}

// ExposeServerPromptEQ applies the EQ predicate on the "expose_server_prompt" field.
func ExposeServerPromptEQ(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldExposeServerPrompt, v))
}

// ExposeServerPromptNEQ applies the NEQ predicate on the "expose_server_prompt" field.
func ExposeServerPromptNEQ(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldExposeServerPrompt, v))
}

// CompactEnabledEQ applies the EQ predicate on the "compact_enabled" field.
func CompactEnabledEQ(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldCompactEnabled, v))
}

// CompactEnabledNEQ applies the NEQ predicate on the "compact_enabled" field.
func CompactEnabledNEQ(v bool) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldCompactEnabled, v))
}

// ActiveTemplateIDEQ applies the EQ predicate on the "active_template_id" field.
func ActiveTemplateIDEQ(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldActiveTemplateID, v))
}

// ActiveTemplateIDNEQ applies the NEQ predicate on the "active_template_id" field.
func ActiveTemplateIDNEQ(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldActiveTemplateID, v))
}

// ActiveTemplateIDIn applies the In predicate on the "active_template_id" field.
func ActiveTemplateIDIn(vs ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIn(FieldActiveTemplateID, vs...))
}

// ActiveTemplateIDNotIn applies the NotIn predicate on the "active_template_id" field.
func ActiveTemplateIDNotIn(vs ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotIn(FieldActiveTemplateID, vs...))
}

// ActiveTemplateIDIsNil applies the IsNil predicate on the "active_template_id" field.
func ActiveTemplateIDIsNil() predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIsNull(FieldActiveTemplateID))
}

// ActiveTemplateIDNotNil applies the NotNil predicate on the "active_template_id" field.
func ActiveTemplateIDNotNil() predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotNull(FieldActiveTemplateID))
}

// ActiveVersionIDEQ applies the EQ predicate on the "active_version_id" field.
func ActiveVersionIDEQ(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldActiveVersionID, v))
}

// ActiveVersionIDNEQ applies the NEQ predicate on the "active_version_id" field.
func ActiveVersionIDNEQ(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldActiveVersionID, v))
}

// ActiveVersionIDIn applies the In predicate on the "active_version_id" field.
func ActiveVersionIDIn(vs ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIn(FieldActiveVersionID, vs...))
}

// ActiveVersionIDNotIn applies the NotIn predicate on the "active_version_id" field.
func ActiveVersionIDNotIn(vs ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotIn(FieldActiveVersionID, vs...))
}

// ActiveVersionIDIsNil applies the IsNil predicate on the "active_version_id" field.
func ActiveVersionIDIsNil() predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIsNull(FieldActiveVersionID))
}

// ActiveVersionIDNotNil applies the NotNil predicate on the "active_version_id" field.
func ActiveVersionIDNotNil() predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotNull(FieldActiveVersionID))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldLTE(FieldRevision, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasActiveTemplate applies the HasEdge predicate on the "active_template" edge.
func HasActiveTemplate() predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActiveTemplateTable, ActiveTemplateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActiveTemplateWith applies the HasEdge predicate on the "active_template" edge with a given conditions (other predicates).
func HasActiveTemplateWith(preds ...predicate.SystemPromptTemplate) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(func(s *sql.Selector) {
		step := newActiveTemplateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActiveVersion applies the HasEdge predicate on the "active_version" edge.
func HasActiveVersion() predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActiveVersionTable, ActiveVersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActiveVersionWith applies the HasEdge predicate on the "active_version" edge with a given conditions (other predicates).
func HasActiveVersionWith(preds ...predicate.SystemPromptTemplateVersion) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(func(s *sql.Selector) {
		step := newActiveVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SystemPromptRuntime) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SystemPromptRuntime) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SystemPromptRuntime) predicate.SystemPromptRuntime {
	return predicate.SystemPromptRuntime(sql.NotPredicates(p))
}
