// Code generated by ent, DO NOT EDIT.

package accounttag

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldName, v))
}

// NormalizedName applies equality check predicate on the "normalized_name" field. It's identical to NormalizedNameEQ.
func NormalizedName(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldNormalizedName, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldContainsFold(FieldName, v))
}

// NormalizedNameEQ applies the EQ predicate on the "normalized_name" field.
func NormalizedNameEQ(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldNormalizedName, v))
}

// NormalizedNameNEQ applies the NEQ predicate on the "normalized_name" field.
func NormalizedNameNEQ(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNEQ(FieldNormalizedName, v))
}

// NormalizedNameIn applies the In predicate on the "normalized_name" field.
func NormalizedNameIn(vs ...string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldIn(FieldNormalizedName, vs...))
}

// NormalizedNameNotIn applies the NotIn predicate on the "normalized_name" field.
func NormalizedNameNotIn(vs ...string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNotIn(FieldNormalizedName, vs...))
}

// NormalizedNameGT applies the GT predicate on the "normalized_name" field.
func NormalizedNameGT(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGT(FieldNormalizedName, v))
}

// NormalizedNameGTE applies the GTE predicate on the "normalized_name" field.
func NormalizedNameGTE(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGTE(FieldNormalizedName, v))
}

// NormalizedNameLT applies the LT predicate on the "normalized_name" field.
func NormalizedNameLT(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLT(FieldNormalizedName, v))
}

// NormalizedNameLTE applies the LTE predicate on the "normalized_name" field.
func NormalizedNameLTE(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLTE(FieldNormalizedName, v))
}

// NormalizedNameContains applies the Contains predicate on the "normalized_name" field.
func NormalizedNameContains(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldContains(FieldNormalizedName, v))
}

// NormalizedNameHasPrefix applies the HasPrefix predicate on the "normalized_name" field.
func NormalizedNameHasPrefix(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldHasPrefix(FieldNormalizedName, v))
}

// NormalizedNameHasSuffix applies the HasSuffix predicate on the "normalized_name" field.
func NormalizedNameHasSuffix(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldHasSuffix(FieldNormalizedName, v))
}

// NormalizedNameEqualFold applies the EqualFold predicate on the "normalized_name" field.
func NormalizedNameEqualFold(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEqualFold(FieldNormalizedName, v))
}

// NormalizedNameContainsFold applies the ContainsFold predicate on the "normalized_name" field.
func NormalizedNameContainsFold(v string) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldContainsFold(FieldNormalizedName, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.AccountTag {
	return predicate.AccountTag(sql.FieldLTE(FieldSortOrder, v))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.AccountTag {
	return predicate.AccountTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AccountsTable, AccountsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.AccountTag {
	return predicate.AccountTag(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccountTagBindings applies the HasEdge predicate on the "account_tag_bindings" edge.
func HasAccountTagBindings() predicate.AccountTag {
	return predicate.AccountTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AccountTagBindingsTable, AccountTagBindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountTagBindingsWith applies the HasEdge predicate on the "account_tag_bindings" edge with a given conditions (other predicates).
func HasAccountTagBindingsWith(preds ...predicate.AccountTagBinding) predicate.AccountTag {
	return predicate.AccountTag(func(s *sql.Selector) {
		step := newAccountTagBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountTag) predicate.AccountTag {
	return predicate.AccountTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountTag) predicate.AccountTag {
	return predicate.AccountTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountTag) predicate.AccountTag {
	return predicate.AccountTag(sql.NotPredicates(p))
}
