// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accounttag"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountTagUpdate is the builder for updating AccountTag entities.
type AccountTagUpdate struct {
	config
	hooks    []Hook
	mutation *AccountTagMutation
}

// Where appends a list predicates to the AccountTagUpdate builder.
func (_u *AccountTagUpdate) Where(ps ...predicate.AccountTag) *AccountTagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountTagUpdate) SetUpdatedAt(v time.Time) *AccountTagUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountTagUpdate) SetName(v string) *AccountTagUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountTagUpdate) SetNillableName(v *string) *AccountTagUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *AccountTagUpdate) SetNormalizedName(v string) *AccountTagUpdate {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *AccountTagUpdate) SetNillableNormalizedName(v *string) *AccountTagUpdate {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AccountTagUpdate) SetSortOrder(v int) *AccountTagUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AccountTagUpdate) SetNillableSortOrder(v *int) *AccountTagUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AccountTagUpdate) AddSortOrder(v int) *AccountTagUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *AccountTagUpdate) AddAccountIDs(ids ...int64) *AccountTagUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *AccountTagUpdate) AddAccounts(v ...*Account) *AccountTagUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the AccountTagMutation object of the builder.
func (_u *AccountTagUpdate) Mutation() *AccountTagMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *AccountTagUpdate) ClearAccounts() *AccountTagUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *AccountTagUpdate) RemoveAccountIDs(ids ...int64) *AccountTagUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *AccountTagUpdate) RemoveAccounts(v ...*Account) *AccountTagUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountTagUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountTagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountTagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountTagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountTagUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accounttag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountTagUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accounttag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountTag.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedName(); ok {
		if err := accounttag.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "AccountTag.normalized_name": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountTagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accounttag.Table, accounttag.Columns, sqlgraph.NewFieldSpec(accounttag.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accounttag.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accounttag.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(accounttag.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(accounttag.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(accounttag.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   accounttag.AccountsTable,
			Columns: accounttag.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		createE := &AccountTagBindingCreate{config: _u.config, mutation: newAccountTagBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   accounttag.AccountsTable,
			Columns: accounttag.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountTagBindingCreate{config: _u.config, mutation: newAccountTagBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   accounttag.AccountsTable,
			Columns: accounttag.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountTagBindingCreate{config: _u.config, mutation: newAccountTagBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounttag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountTagUpdateOne is the builder for updating a single AccountTag entity.
type AccountTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountTagMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountTagUpdateOne) SetUpdatedAt(v time.Time) *AccountTagUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountTagUpdateOne) SetName(v string) *AccountTagUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountTagUpdateOne) SetNillableName(v *string) *AccountTagUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *AccountTagUpdateOne) SetNormalizedName(v string) *AccountTagUpdateOne {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *AccountTagUpdateOne) SetNillableNormalizedName(v *string) *AccountTagUpdateOne {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AccountTagUpdateOne) SetSortOrder(v int) *AccountTagUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AccountTagUpdateOne) SetNillableSortOrder(v *int) *AccountTagUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AccountTagUpdateOne) AddSortOrder(v int) *AccountTagUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *AccountTagUpdateOne) AddAccountIDs(ids ...int64) *AccountTagUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *AccountTagUpdateOne) AddAccounts(v ...*Account) *AccountTagUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the AccountTagMutation object of the builder.
func (_u *AccountTagUpdateOne) Mutation() *AccountTagMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *AccountTagUpdateOne) ClearAccounts() *AccountTagUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *AccountTagUpdateOne) RemoveAccountIDs(ids ...int64) *AccountTagUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *AccountTagUpdateOne) RemoveAccounts(v ...*Account) *AccountTagUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the AccountTagUpdate builder.
func (_u *AccountTagUpdateOne) Where(ps ...predicate.AccountTag) *AccountTagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountTagUpdateOne) Select(field string, fields ...string) *AccountTagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountTag entity.
func (_u *AccountTagUpdateOne) Save(ctx context.Context) (*AccountTag, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountTagUpdateOne) SaveX(ctx context.Context) *AccountTag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountTagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountTagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountTagUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accounttag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountTagUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accounttag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountTag.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedName(); ok {
		if err := accounttag.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "AccountTag.normalized_name": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountTagUpdateOne) sqlSave(ctx context.Context) (_node *AccountTag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accounttag.Table, accounttag.Columns, sqlgraph.NewFieldSpec(accounttag.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accounttag.FieldID)
		for _, f := range fields {
			if !accounttag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accounttag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accounttag.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accounttag.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(accounttag.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(accounttag.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(accounttag.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   accounttag.AccountsTable,
			Columns: accounttag.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		createE := &AccountTagBindingCreate{config: _u.config, mutation: newAccountTagBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   accounttag.AccountsTable,
			Columns: accounttag.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountTagBindingCreate{config: _u.config, mutation: newAccountTagBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   accounttag.AccountsTable,
			Columns: accounttag.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountTagBindingCreate{config: _u.config, mutation: newAccountTagBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountTag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounttag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
