// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accounttag"
	"github.com/Wei-Shaw/sub2api/ent/accounttagbinding"
)

// AccountTagBindingCreate is the builder for creating a AccountTagBinding entity.
type AccountTagBindingCreate struct {
	config
	mutation *AccountTagBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountTagBindingCreate) SetAccountID(v int64) *AccountTagBindingCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetTagID sets the "tag_id" field.
func (_c *AccountTagBindingCreate) SetTagID(v int64) *AccountTagBindingCreate {
	_c.mutation.SetTagID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountTagBindingCreate) SetCreatedAt(v time.Time) *AccountTagBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountTagBindingCreate) SetNillableCreatedAt(v *time.Time) *AccountTagBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountTagBindingCreate) SetAccount(v *Account) *AccountTagBindingCreate {
	return _c.SetAccountID(v.ID)
}

// SetTag sets the "tag" edge to the AccountTag entity.
func (_c *AccountTagBindingCreate) SetTag(v *AccountTag) *AccountTagBindingCreate {
	return _c.SetTagID(v.ID)
}

// Mutation returns the AccountTagBindingMutation object of the builder.
func (_c *AccountTagBindingCreate) Mutation() *AccountTagBindingMutation {
	return _c.mutation
}

// Save creates the AccountTagBinding in the database.
func (_c *AccountTagBindingCreate) Save(ctx context.Context) (*AccountTagBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountTagBindingCreate) SaveX(ctx context.Context) *AccountTagBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountTagBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountTagBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountTagBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accounttagbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountTagBindingCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountTagBinding.account_id"`)}
	}
	if _, ok := _c.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "AccountTagBinding.tag_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountTagBinding.created_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountTagBinding.account"`)}
	}
	if len(_c.mutation.TagIDs()) == 0 {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "AccountTagBinding.tag"`)}
	}
	return nil
}

func (_c *AccountTagBindingCreate) sqlSave(ctx context.Context) (*AccountTagBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *AccountTagBindingCreate) createSpec() (*AccountTagBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountTagBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accounttagbinding.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accounttagbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.AccountTable,
			Columns: []string{accounttagbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.TagTable,
			Columns: []string{accounttagbinding.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accounttag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountTagBinding.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountTagBindingUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountTagBindingCreate) OnConflict(opts ...sql.ConflictOption) *AccountTagBindingUpsertOne {
	_c.conflict = opts
	return &AccountTagBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountTagBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountTagBindingCreate) OnConflictColumns(columns ...string) *AccountTagBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountTagBindingUpsertOne{
		create: _c,
	}
}

type (
	// AccountTagBindingUpsertOne is the builder for "upsert"-ing
	//  one AccountTagBinding node.
	AccountTagBindingUpsertOne struct {
		create *AccountTagBindingCreate
	}

	// AccountTagBindingUpsert is the "OnConflict" setter.
	AccountTagBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountTagBindingUpsert) SetAccountID(v int64) *AccountTagBindingUpsert {
	u.Set(accounttagbinding.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountTagBindingUpsert) UpdateAccountID() *AccountTagBindingUpsert {
	u.SetExcluded(accounttagbinding.FieldAccountID)
	return u
}

// SetTagID sets the "tag_id" field.
func (u *AccountTagBindingUpsert) SetTagID(v int64) *AccountTagBindingUpsert {
	u.Set(accounttagbinding.FieldTagID, v)
	return u
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *AccountTagBindingUpsert) UpdateTagID() *AccountTagBindingUpsert {
	u.SetExcluded(accounttagbinding.FieldTagID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountTagBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountTagBindingUpsertOne) UpdateNewValues() *AccountTagBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accounttagbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountTagBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountTagBindingUpsertOne) Ignore() *AccountTagBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountTagBindingUpsertOne) DoNothing() *AccountTagBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountTagBindingCreate.OnConflict
// documentation for more info.
func (u *AccountTagBindingUpsertOne) Update(set func(*AccountTagBindingUpsert)) *AccountTagBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountTagBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountTagBindingUpsertOne) SetAccountID(v int64) *AccountTagBindingUpsertOne {
	return u.Update(func(s *AccountTagBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountTagBindingUpsertOne) UpdateAccountID() *AccountTagBindingUpsertOne {
	return u.Update(func(s *AccountTagBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetTagID sets the "tag_id" field.
func (u *AccountTagBindingUpsertOne) SetTagID(v int64) *AccountTagBindingUpsertOne {
	return u.Update(func(s *AccountTagBindingUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *AccountTagBindingUpsertOne) UpdateTagID() *AccountTagBindingUpsertOne {
	return u.Update(func(s *AccountTagBindingUpsert) {
		s.UpdateTagID()
	})
}

// Exec executes the query.
func (u *AccountTagBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountTagBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountTagBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// AccountTagBindingCreateBulk is the builder for creating many AccountTagBinding entities in bulk.
type AccountTagBindingCreateBulk struct {
	config
	err      error
	builders []*AccountTagBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountTagBinding entities in the database.
func (_c *AccountTagBindingCreateBulk) Save(ctx context.Context) ([]*AccountTagBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountTagBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountTagBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountTagBindingCreateBulk) SaveX(ctx context.Context) []*AccountTagBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountTagBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountTagBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountTagBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountTagBindingUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountTagBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountTagBindingUpsertBulk {
	_c.conflict = opts
	return &AccountTagBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountTagBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountTagBindingCreateBulk) OnConflictColumns(columns ...string) *AccountTagBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountTagBindingUpsertBulk{
		create: _c,
	}
}

// AccountTagBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountTagBinding nodes.
type AccountTagBindingUpsertBulk struct {
	create *AccountTagBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountTagBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountTagBindingUpsertBulk) UpdateNewValues() *AccountTagBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accounttagbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountTagBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountTagBindingUpsertBulk) Ignore() *AccountTagBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountTagBindingUpsertBulk) DoNothing() *AccountTagBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountTagBindingCreateBulk.OnConflict
// documentation for more info.
func (u *AccountTagBindingUpsertBulk) Update(set func(*AccountTagBindingUpsert)) *AccountTagBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountTagBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountTagBindingUpsertBulk) SetAccountID(v int64) *AccountTagBindingUpsertBulk {
	return u.Update(func(s *AccountTagBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountTagBindingUpsertBulk) UpdateAccountID() *AccountTagBindingUpsertBulk {
	return u.Update(func(s *AccountTagBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetTagID sets the "tag_id" field.
func (u *AccountTagBindingUpsertBulk) SetTagID(v int64) *AccountTagBindingUpsertBulk {
	return u.Update(func(s *AccountTagBindingUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *AccountTagBindingUpsertBulk) UpdateTagID() *AccountTagBindingUpsertBulk {
	return u.Update(func(s *AccountTagBindingUpsert) {
		s.UpdateTagID()
	})
}

// Exec executes the query.
func (u *AccountTagBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountTagBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountTagBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountTagBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
