// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accounttag"
	"github.com/Wei-Shaw/sub2api/ent/accounttagbinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountTagBindingUpdate is the builder for updating AccountTagBinding entities.
type AccountTagBindingUpdate struct {
	config
	hooks    []Hook
	mutation *AccountTagBindingMutation
}

// Where appends a list predicates to the AccountTagBindingUpdate builder.
func (_u *AccountTagBindingUpdate) Where(ps ...predicate.AccountTagBinding) *AccountTagBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountTagBindingUpdate) SetAccountID(v int64) *AccountTagBindingUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountTagBindingUpdate) SetNillableAccountID(v *int64) *AccountTagBindingUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *AccountTagBindingUpdate) SetTagID(v int64) *AccountTagBindingUpdate {
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *AccountTagBindingUpdate) SetNillableTagID(v *int64) *AccountTagBindingUpdate {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountTagBindingUpdate) SetAccount(v *Account) *AccountTagBindingUpdate {
	return _u.SetAccountID(v.ID)
}

// SetTag sets the "tag" edge to the AccountTag entity.
func (_u *AccountTagBindingUpdate) SetTag(v *AccountTag) *AccountTagBindingUpdate {
	return _u.SetTagID(v.ID)
}

// Mutation returns the AccountTagBindingMutation object of the builder.
func (_u *AccountTagBindingUpdate) Mutation() *AccountTagBindingMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountTagBindingUpdate) ClearAccount() *AccountTagBindingUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearTag clears the "tag" edge to the AccountTag entity.
func (_u *AccountTagBindingUpdate) ClearTag() *AccountTagBindingUpdate {
	_u.mutation.ClearTag()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountTagBindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountTagBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountTagBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountTagBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountTagBindingUpdate) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountTagBinding.account"`)
	}
	if _u.mutation.TagCleared() && len(_u.mutation.TagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountTagBinding.tag"`)
	}
	return nil
}

func (_u *AccountTagBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accounttagbinding.Table, accounttagbinding.Columns, sqlgraph.NewFieldSpec(accounttagbinding.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accounttagbinding.FieldTagID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.AccountTable,
			Columns: []string{accounttagbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.AccountTable,
			Columns: []string{accounttagbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.TagTable,
			Columns: []string{accounttagbinding.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accounttag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.TagTable,
			Columns: []string{accounttagbinding.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accounttag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounttagbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountTagBindingUpdateOne is the builder for updating a single AccountTagBinding entity.
type AccountTagBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountTagBindingMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountTagBindingUpdateOne) SetAccountID(v int64) *AccountTagBindingUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountTagBindingUpdateOne) SetNillableAccountID(v *int64) *AccountTagBindingUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *AccountTagBindingUpdateOne) SetTagID(v int64) *AccountTagBindingUpdateOne {
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *AccountTagBindingUpdateOne) SetNillableTagID(v *int64) *AccountTagBindingUpdateOne {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountTagBindingUpdateOne) SetAccount(v *Account) *AccountTagBindingUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetTag sets the "tag" edge to the AccountTag entity.
func (_u *AccountTagBindingUpdateOne) SetTag(v *AccountTag) *AccountTagBindingUpdateOne {
	return _u.SetTagID(v.ID)
}

// Mutation returns the AccountTagBindingMutation object of the builder.
func (_u *AccountTagBindingUpdateOne) Mutation() *AccountTagBindingMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountTagBindingUpdateOne) ClearAccount() *AccountTagBindingUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearTag clears the "tag" edge to the AccountTag entity.
func (_u *AccountTagBindingUpdateOne) ClearTag() *AccountTagBindingUpdateOne {
	_u.mutation.ClearTag()
	return _u
}

// Where appends a list predicates to the AccountTagBindingUpdate builder.
func (_u *AccountTagBindingUpdateOne) Where(ps ...predicate.AccountTagBinding) *AccountTagBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountTagBindingUpdateOne) Select(field string, fields ...string) *AccountTagBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountTagBinding entity.
func (_u *AccountTagBindingUpdateOne) Save(ctx context.Context) (*AccountTagBinding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountTagBindingUpdateOne) SaveX(ctx context.Context) *AccountTagBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountTagBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountTagBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountTagBindingUpdateOne) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountTagBinding.account"`)
	}
	if _u.mutation.TagCleared() && len(_u.mutation.TagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountTagBinding.tag"`)
	}
	return nil
}

func (_u *AccountTagBindingUpdateOne) sqlSave(ctx context.Context) (_node *AccountTagBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accounttagbinding.Table, accounttagbinding.Columns, sqlgraph.NewFieldSpec(accounttagbinding.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accounttagbinding.FieldTagID, field.TypeInt64))
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "AccountTagBinding.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.TagID(); !ok {
		return nil, &ValidationError{Name: "tag_id", err: errors.New(`ent: missing "AccountTagBinding.tag_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !accounttagbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.AccountTable,
			Columns: []string{accounttagbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.AccountTable,
			Columns: []string{accounttagbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.TagTable,
			Columns: []string{accounttagbinding.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accounttag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accounttagbinding.TagTable,
			Columns: []string{accounttagbinding.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accounttag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountTagBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounttagbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
