// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountfolder"
)

// AccountFolderCreate is the builder for creating a AccountFolder entity.
type AccountFolderCreate struct {
	config
	mutation *AccountFolderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountFolderCreate) SetCreatedAt(v time.Time) *AccountFolderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountFolderCreate) SetNillableCreatedAt(v *time.Time) *AccountFolderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountFolderCreate) SetUpdatedAt(v time.Time) *AccountFolderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountFolderCreate) SetNillableUpdatedAt(v *time.Time) *AccountFolderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AccountFolderCreate) SetName(v string) *AccountFolderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNormalizedName sets the "normalized_name" field.
func (_c *AccountFolderCreate) SetNormalizedName(v string) *AccountFolderCreate {
	_c.mutation.SetNormalizedName(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *AccountFolderCreate) SetSortOrder(v int) *AccountFolderCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *AccountFolderCreate) SetNillableSortOrder(v *int) *AccountFolderCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *AccountFolderCreate) AddAccountIDs(ids ...int64) *AccountFolderCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *AccountFolderCreate) AddAccounts(v ...*Account) *AccountFolderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the AccountFolderMutation object of the builder.
func (_c *AccountFolderCreate) Mutation() *AccountFolderMutation {
	return _c.mutation
}

// Save creates the AccountFolder in the database.
func (_c *AccountFolderCreate) Save(ctx context.Context) (*AccountFolder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountFolderCreate) SaveX(ctx context.Context) *AccountFolder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountFolderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountFolderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountFolderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountfolder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountfolder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := accountfolder.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountFolderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountFolder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountFolder.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccountFolder.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accountfolder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountFolder.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedName(); !ok {
		return &ValidationError{Name: "normalized_name", err: errors.New(`ent: missing required field "AccountFolder.normalized_name"`)}
	}
	if v, ok := _c.mutation.NormalizedName(); ok {
		if err := accountfolder.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "AccountFolder.normalized_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "AccountFolder.sort_order"`)}
	}
	return nil
}

func (_c *AccountFolderCreate) sqlSave(ctx context.Context) (*AccountFolder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountFolderCreate) createSpec() (*AccountFolder, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountFolder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountfolder.Table, sqlgraph.NewFieldSpec(accountfolder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountfolder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountfolder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accountfolder.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NormalizedName(); ok {
		_spec.SetField(accountfolder.FieldNormalizedName, field.TypeString, value)
		_node.NormalizedName = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(accountfolder.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountfolder.AccountsTable,
			Columns: []string{accountfolder.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountFolder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountFolderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountFolderCreate) OnConflict(opts ...sql.ConflictOption) *AccountFolderUpsertOne {
	_c.conflict = opts
	return &AccountFolderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountFolder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountFolderCreate) OnConflictColumns(columns ...string) *AccountFolderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountFolderUpsertOne{
		create: _c,
	}
}

type (
	// AccountFolderUpsertOne is the builder for "upsert"-ing
	//  one AccountFolder node.
	AccountFolderUpsertOne struct {
		create *AccountFolderCreate
	}

	// AccountFolderUpsert is the "OnConflict" setter.
	AccountFolderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountFolderUpsert) SetUpdatedAt(v time.Time) *AccountFolderUpsert {
	u.Set(accountfolder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountFolderUpsert) UpdateUpdatedAt() *AccountFolderUpsert {
	u.SetExcluded(accountfolder.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *AccountFolderUpsert) SetName(v string) *AccountFolderUpsert {
	u.Set(accountfolder.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountFolderUpsert) UpdateName() *AccountFolderUpsert {
	u.SetExcluded(accountfolder.FieldName)
	return u
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountFolderUpsert) SetNormalizedName(v string) *AccountFolderUpsert {
	u.Set(accountfolder.FieldNormalizedName, v)
	return u
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountFolderUpsert) UpdateNormalizedName() *AccountFolderUpsert {
	u.SetExcluded(accountfolder.FieldNormalizedName)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountFolderUpsert) SetSortOrder(v int) *AccountFolderUpsert {
	u.Set(accountfolder.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountFolderUpsert) UpdateSortOrder() *AccountFolderUpsert {
	u.SetExcluded(accountfolder.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountFolderUpsert) AddSortOrder(v int) *AccountFolderUpsert {
	u.Add(accountfolder.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountFolder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountFolderUpsertOne) UpdateNewValues() *AccountFolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountfolder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountFolder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountFolderUpsertOne) Ignore() *AccountFolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountFolderUpsertOne) DoNothing() *AccountFolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountFolderCreate.OnConflict
// documentation for more info.
func (u *AccountFolderUpsertOne) Update(set func(*AccountFolderUpsert)) *AccountFolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountFolderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountFolderUpsertOne) SetUpdatedAt(v time.Time) *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountFolderUpsertOne) UpdateUpdatedAt() *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountFolderUpsertOne) SetName(v string) *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountFolderUpsertOne) UpdateName() *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.UpdateName()
	})
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountFolderUpsertOne) SetNormalizedName(v string) *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.SetNormalizedName(v)
	})
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountFolderUpsertOne) UpdateNormalizedName() *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.UpdateNormalizedName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountFolderUpsertOne) SetSortOrder(v int) *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountFolderUpsertOne) AddSortOrder(v int) *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountFolderUpsertOne) UpdateSortOrder() *AccountFolderUpsertOne {
	return u.Update(func(s *AccountFolderUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *AccountFolderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountFolderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountFolderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountFolderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountFolderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountFolderCreateBulk is the builder for creating many AccountFolder entities in bulk.
type AccountFolderCreateBulk struct {
	config
	err      error
	builders []*AccountFolderCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountFolder entities in the database.
func (_c *AccountFolderCreateBulk) Save(ctx context.Context) ([]*AccountFolder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountFolder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountFolderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountFolderCreateBulk) SaveX(ctx context.Context) []*AccountFolder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountFolderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountFolderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountFolder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountFolderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountFolderCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountFolderUpsertBulk {
	_c.conflict = opts
	return &AccountFolderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountFolder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountFolderCreateBulk) OnConflictColumns(columns ...string) *AccountFolderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountFolderUpsertBulk{
		create: _c,
	}
}

// AccountFolderUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountFolder nodes.
type AccountFolderUpsertBulk struct {
	create *AccountFolderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountFolder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountFolderUpsertBulk) UpdateNewValues() *AccountFolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountfolder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountFolder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountFolderUpsertBulk) Ignore() *AccountFolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountFolderUpsertBulk) DoNothing() *AccountFolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountFolderCreateBulk.OnConflict
// documentation for more info.
func (u *AccountFolderUpsertBulk) Update(set func(*AccountFolderUpsert)) *AccountFolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountFolderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountFolderUpsertBulk) SetUpdatedAt(v time.Time) *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountFolderUpsertBulk) UpdateUpdatedAt() *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountFolderUpsertBulk) SetName(v string) *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountFolderUpsertBulk) UpdateName() *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.UpdateName()
	})
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountFolderUpsertBulk) SetNormalizedName(v string) *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.SetNormalizedName(v)
	})
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountFolderUpsertBulk) UpdateNormalizedName() *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.UpdateNormalizedName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountFolderUpsertBulk) SetSortOrder(v int) *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountFolderUpsertBulk) AddSortOrder(v int) *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountFolderUpsertBulk) UpdateSortOrder() *AccountFolderUpsertBulk {
	return u.Update(func(s *AccountFolderUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *AccountFolderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountFolderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountFolderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountFolderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
