// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accounttag"
)

// AccountTagCreate is the builder for creating a AccountTag entity.
type AccountTagCreate struct {
	config
	mutation *AccountTagMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountTagCreate) SetCreatedAt(v time.Time) *AccountTagCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountTagCreate) SetNillableCreatedAt(v *time.Time) *AccountTagCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountTagCreate) SetUpdatedAt(v time.Time) *AccountTagCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountTagCreate) SetNillableUpdatedAt(v *time.Time) *AccountTagCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AccountTagCreate) SetName(v string) *AccountTagCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNormalizedName sets the "normalized_name" field.
func (_c *AccountTagCreate) SetNormalizedName(v string) *AccountTagCreate {
	_c.mutation.SetNormalizedName(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *AccountTagCreate) SetSortOrder(v int) *AccountTagCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *AccountTagCreate) SetNillableSortOrder(v *int) *AccountTagCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *AccountTagCreate) AddAccountIDs(ids ...int64) *AccountTagCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *AccountTagCreate) AddAccounts(v ...*Account) *AccountTagCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the AccountTagMutation object of the builder.
func (_c *AccountTagCreate) Mutation() *AccountTagMutation {
	return _c.mutation
}

// Save creates the AccountTag in the database.
func (_c *AccountTagCreate) Save(ctx context.Context) (*AccountTag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountTagCreate) SaveX(ctx context.Context) *AccountTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountTagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountTagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountTagCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accounttag.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accounttag.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := accounttag.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountTagCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountTag.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountTag.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccountTag.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accounttag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountTag.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedName(); !ok {
		return &ValidationError{Name: "normalized_name", err: errors.New(`ent: missing required field "AccountTag.normalized_name"`)}
	}
	if v, ok := _c.mutation.NormalizedName(); ok {
		if err := accounttag.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "AccountTag.normalized_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "AccountTag.sort_order"`)}
	}
	return nil
}

func (_c *AccountTagCreate) sqlSave(ctx context.Context) (*AccountTag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountTagCreate) createSpec() (*AccountTag, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountTag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accounttag.Table, sqlgraph.NewFieldSpec(accounttag.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accounttag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accounttag.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accounttag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NormalizedName(); ok {
		_spec.SetField(accounttag.FieldNormalizedName, field.TypeString, value)
		_node.NormalizedName = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(accounttag.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   accounttag.AccountsTable,
			Columns: accounttag.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AccountTagBindingCreate{config: _c.config, mutation: newAccountTagBindingMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountTag.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountTagUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountTagCreate) OnConflict(opts ...sql.ConflictOption) *AccountTagUpsertOne {
	_c.conflict = opts
	return &AccountTagUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountTagCreate) OnConflictColumns(columns ...string) *AccountTagUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountTagUpsertOne{
		create: _c,
	}
}

type (
	// AccountTagUpsertOne is the builder for "upsert"-ing
	//  one AccountTag node.
	AccountTagUpsertOne struct {
		create *AccountTagCreate
	}

	// AccountTagUpsert is the "OnConflict" setter.
	AccountTagUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountTagUpsert) SetUpdatedAt(v time.Time) *AccountTagUpsert {
	u.Set(accounttag.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountTagUpsert) UpdateUpdatedAt() *AccountTagUpsert {
	u.SetExcluded(accounttag.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *AccountTagUpsert) SetName(v string) *AccountTagUpsert {
	u.Set(accounttag.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountTagUpsert) UpdateName() *AccountTagUpsert {
	u.SetExcluded(accounttag.FieldName)
	return u
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountTagUpsert) SetNormalizedName(v string) *AccountTagUpsert {
	u.Set(accounttag.FieldNormalizedName, v)
	return u
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountTagUpsert) UpdateNormalizedName() *AccountTagUpsert {
	u.SetExcluded(accounttag.FieldNormalizedName)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountTagUpsert) SetSortOrder(v int) *AccountTagUpsert {
	u.Set(accounttag.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountTagUpsert) UpdateSortOrder() *AccountTagUpsert {
	u.SetExcluded(accounttag.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountTagUpsert) AddSortOrder(v int) *AccountTagUpsert {
	u.Add(accounttag.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountTagUpsertOne) UpdateNewValues() *AccountTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accounttag.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountTag.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountTagUpsertOne) Ignore() *AccountTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountTagUpsertOne) DoNothing() *AccountTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountTagCreate.OnConflict
// documentation for more info.
func (u *AccountTagUpsertOne) Update(set func(*AccountTagUpsert)) *AccountTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountTagUpsertOne) SetUpdatedAt(v time.Time) *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountTagUpsertOne) UpdateUpdatedAt() *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountTagUpsertOne) SetName(v string) *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountTagUpsertOne) UpdateName() *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.UpdateName()
	})
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountTagUpsertOne) SetNormalizedName(v string) *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.SetNormalizedName(v)
	})
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountTagUpsertOne) UpdateNormalizedName() *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.UpdateNormalizedName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountTagUpsertOne) SetSortOrder(v int) *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountTagUpsertOne) AddSortOrder(v int) *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountTagUpsertOne) UpdateSortOrder() *AccountTagUpsertOne {
	return u.Update(func(s *AccountTagUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *AccountTagUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountTagCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountTagUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountTagUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountTagUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountTagCreateBulk is the builder for creating many AccountTag entities in bulk.
type AccountTagCreateBulk struct {
	config
	err      error
	builders []*AccountTagCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountTag entities in the database.
func (_c *AccountTagCreateBulk) Save(ctx context.Context) ([]*AccountTag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountTag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountTagCreateBulk) SaveX(ctx context.Context) []*AccountTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountTagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountTagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountTag.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountTagUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountTagCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountTagUpsertBulk {
	_c.conflict = opts
	return &AccountTagUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountTagCreateBulk) OnConflictColumns(columns ...string) *AccountTagUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountTagUpsertBulk{
		create: _c,
	}
}

// AccountTagUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountTag nodes.
type AccountTagUpsertBulk struct {
	create *AccountTagCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountTagUpsertBulk) UpdateNewValues() *AccountTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accounttag.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountTag.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountTagUpsertBulk) Ignore() *AccountTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountTagUpsertBulk) DoNothing() *AccountTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountTagCreateBulk.OnConflict
// documentation for more info.
func (u *AccountTagUpsertBulk) Update(set func(*AccountTagUpsert)) *AccountTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountTagUpsertBulk) SetUpdatedAt(v time.Time) *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountTagUpsertBulk) UpdateUpdatedAt() *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountTagUpsertBulk) SetName(v string) *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountTagUpsertBulk) UpdateName() *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.UpdateName()
	})
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountTagUpsertBulk) SetNormalizedName(v string) *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.SetNormalizedName(v)
	})
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountTagUpsertBulk) UpdateNormalizedName() *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.UpdateNormalizedName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountTagUpsertBulk) SetSortOrder(v int) *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountTagUpsertBulk) AddSortOrder(v int) *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountTagUpsertBulk) UpdateSortOrder() *AccountTagUpsertBulk {
	return u.Update(func(s *AccountTagUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *AccountTagUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountTagCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountTagCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountTagUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
