// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountfolder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountFolderUpdate is the builder for updating AccountFolder entities.
type AccountFolderUpdate struct {
	config
	hooks    []Hook
	mutation *AccountFolderMutation
}

// Where appends a list predicates to the AccountFolderUpdate builder.
func (_u *AccountFolderUpdate) Where(ps ...predicate.AccountFolder) *AccountFolderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountFolderUpdate) SetUpdatedAt(v time.Time) *AccountFolderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountFolderUpdate) SetName(v string) *AccountFolderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountFolderUpdate) SetNillableName(v *string) *AccountFolderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *AccountFolderUpdate) SetNormalizedName(v string) *AccountFolderUpdate {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *AccountFolderUpdate) SetNillableNormalizedName(v *string) *AccountFolderUpdate {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AccountFolderUpdate) SetSortOrder(v int) *AccountFolderUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AccountFolderUpdate) SetNillableSortOrder(v *int) *AccountFolderUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AccountFolderUpdate) AddSortOrder(v int) *AccountFolderUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *AccountFolderUpdate) AddAccountIDs(ids ...int64) *AccountFolderUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *AccountFolderUpdate) AddAccounts(v ...*Account) *AccountFolderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the AccountFolderMutation object of the builder.
func (_u *AccountFolderUpdate) Mutation() *AccountFolderMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *AccountFolderUpdate) ClearAccounts() *AccountFolderUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *AccountFolderUpdate) RemoveAccountIDs(ids ...int64) *AccountFolderUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *AccountFolderUpdate) RemoveAccounts(v ...*Account) *AccountFolderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountFolderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountFolderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountFolderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountFolderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountFolderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountfolder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountFolderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountfolder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountFolder.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedName(); ok {
		if err := accountfolder.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "AccountFolder.normalized_name": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountFolderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountfolder.Table, accountfolder.Columns, sqlgraph.NewFieldSpec(accountfolder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountfolder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountfolder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(accountfolder.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(accountfolder.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(accountfolder.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountfolder.AccountsTable,
			Columns: []string{accountfolder.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountfolder.AccountsTable,
			Columns: []string{accountfolder.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountfolder.AccountsTable,
			Columns: []string{accountfolder.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountfolder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountFolderUpdateOne is the builder for updating a single AccountFolder entity.
type AccountFolderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountFolderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountFolderUpdateOne) SetUpdatedAt(v time.Time) *AccountFolderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountFolderUpdateOne) SetName(v string) *AccountFolderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountFolderUpdateOne) SetNillableName(v *string) *AccountFolderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *AccountFolderUpdateOne) SetNormalizedName(v string) *AccountFolderUpdateOne {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *AccountFolderUpdateOne) SetNillableNormalizedName(v *string) *AccountFolderUpdateOne {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AccountFolderUpdateOne) SetSortOrder(v int) *AccountFolderUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AccountFolderUpdateOne) SetNillableSortOrder(v *int) *AccountFolderUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AccountFolderUpdateOne) AddSortOrder(v int) *AccountFolderUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *AccountFolderUpdateOne) AddAccountIDs(ids ...int64) *AccountFolderUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *AccountFolderUpdateOne) AddAccounts(v ...*Account) *AccountFolderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the AccountFolderMutation object of the builder.
func (_u *AccountFolderUpdateOne) Mutation() *AccountFolderMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *AccountFolderUpdateOne) ClearAccounts() *AccountFolderUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *AccountFolderUpdateOne) RemoveAccountIDs(ids ...int64) *AccountFolderUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *AccountFolderUpdateOne) RemoveAccounts(v ...*Account) *AccountFolderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the AccountFolderUpdate builder.
func (_u *AccountFolderUpdateOne) Where(ps ...predicate.AccountFolder) *AccountFolderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountFolderUpdateOne) Select(field string, fields ...string) *AccountFolderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountFolder entity.
func (_u *AccountFolderUpdateOne) Save(ctx context.Context) (*AccountFolder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountFolderUpdateOne) SaveX(ctx context.Context) *AccountFolder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountFolderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountFolderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountFolderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountfolder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountFolderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountfolder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountFolder.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedName(); ok {
		if err := accountfolder.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "AccountFolder.normalized_name": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountFolderUpdateOne) sqlSave(ctx context.Context) (_node *AccountFolder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountfolder.Table, accountfolder.Columns, sqlgraph.NewFieldSpec(accountfolder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountFolder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountfolder.FieldID)
		for _, f := range fields {
			if !accountfolder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountfolder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountfolder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountfolder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(accountfolder.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(accountfolder.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(accountfolder.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountfolder.AccountsTable,
			Columns: []string{accountfolder.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountfolder.AccountsTable,
			Columns: []string{accountfolder.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountfolder.AccountsTable,
			Columns: []string{accountfolder.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountFolder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountfolder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
