// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplateversion"
)

// SystemPromptTemplateVersion is the model entity for the SystemPromptTemplateVersion schema.
type SystemPromptTemplateVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TemplateID holds the value of the "template_id" field.
	TemplateID int64 `json:"template_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// ByteLength holds the value of the "byte_length" field.
	ByteLength int `json:"byte_length,omitempty"`
	// CompositionMode holds the value of the "composition_mode" field.
	CompositionMode string `json:"composition_mode,omitempty"`
	// BundleID holds the value of the "bundle_id" field.
	BundleID *string `json:"bundle_id,omitempty"`
	// BundleManifestSha256 holds the value of the "bundle_manifest_sha256" field.
	BundleManifestSha256 *string `json:"bundle_manifest_sha256,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// PublishedBy holds the value of the "published_by" field.
	PublishedBy *int64 `json:"published_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SystemPromptTemplateVersionQuery when eager-loading is set.
	Edges        SystemPromptTemplateVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SystemPromptTemplateVersionEdges holds the relations/edges for other nodes in the graph.
type SystemPromptTemplateVersionEdges struct {
	// Template holds the value of the template edge.
	Template *SystemPromptTemplate `json:"template,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TemplateOrErr returns the Template value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SystemPromptTemplateVersionEdges) TemplateOrErr() (*SystemPromptTemplate, error) {
	if e.Template != nil {
		return e.Template, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: systemprompttemplate.Label}
	}
	return nil, &NotLoadedError{edge: "template"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemPromptTemplateVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systemprompttemplateversion.FieldID, systemprompttemplateversion.FieldTemplateID, systemprompttemplateversion.FieldVersion, systemprompttemplateversion.FieldByteLength, systemprompttemplateversion.FieldCreatedBy, systemprompttemplateversion.FieldPublishedBy:
			values[i] = new(sql.NullInt64)
		case systemprompttemplateversion.FieldBody, systemprompttemplateversion.FieldSha256, systemprompttemplateversion.FieldCompositionMode, systemprompttemplateversion.FieldBundleID, systemprompttemplateversion.FieldBundleManifestSha256, systemprompttemplateversion.FieldNote:
			values[i] = new(sql.NullString)
		case systemprompttemplateversion.FieldPublishedAt, systemprompttemplateversion.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemPromptTemplateVersion fields.
func (_m *SystemPromptTemplateVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systemprompttemplateversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case systemprompttemplateversion.FieldTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = value.Int64
			}
		case systemprompttemplateversion.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case systemprompttemplateversion.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case systemprompttemplateversion.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case systemprompttemplateversion.FieldByteLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field byte_length", values[i])
			} else if value.Valid {
				_m.ByteLength = int(value.Int64)
			}
		case systemprompttemplateversion.FieldCompositionMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field composition_mode", values[i])
			} else if value.Valid {
				_m.CompositionMode = value.String
			}
		case systemprompttemplateversion.FieldBundleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bundle_id", values[i])
			} else if value.Valid {
				_m.BundleID = new(string)
				*_m.BundleID = value.String
			}
		case systemprompttemplateversion.FieldBundleManifestSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bundle_manifest_sha256", values[i])
			} else if value.Valid {
				_m.BundleManifestSha256 = new(string)
				*_m.BundleManifestSha256 = value.String
			}
		case systemprompttemplateversion.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case systemprompttemplateversion.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case systemprompttemplateversion.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case systemprompttemplateversion.FieldPublishedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field published_by", values[i])
			} else if value.Valid {
				_m.PublishedBy = new(int64)
				*_m.PublishedBy = value.Int64
			}
		case systemprompttemplateversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SystemPromptTemplateVersion.
// This includes values selected through modifiers, order, etc.
func (_m *SystemPromptTemplateVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTemplate queries the "template" edge of the SystemPromptTemplateVersion entity.
func (_m *SystemPromptTemplateVersion) QueryTemplate() *SystemPromptTemplateQuery {
	return NewSystemPromptTemplateVersionClient(_m.config).QueryTemplate(_m)
}

// Update returns a builder for updating this SystemPromptTemplateVersion.
// Note that you need to call SystemPromptTemplateVersion.Unwrap() before calling this method if this SystemPromptTemplateVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SystemPromptTemplateVersion) Update() *SystemPromptTemplateVersionUpdateOne {
	return NewSystemPromptTemplateVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SystemPromptTemplateVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SystemPromptTemplateVersion) Unwrap() *SystemPromptTemplateVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemPromptTemplateVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SystemPromptTemplateVersion) String() string {
	var builder strings.Builder
	builder.WriteString("SystemPromptTemplateVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("byte_length=")
	builder.WriteString(fmt.Sprintf("%v", _m.ByteLength))
	builder.WriteString(", ")
	builder.WriteString("composition_mode=")
	builder.WriteString(_m.CompositionMode)
	builder.WriteString(", ")
	if v := _m.BundleID; v != nil {
		builder.WriteString("bundle_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BundleManifestSha256; v != nil {
		builder.WriteString("bundle_manifest_sha256=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PublishedBy; v != nil {
		builder.WriteString("published_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SystemPromptTemplateVersions is a parsable slice of SystemPromptTemplateVersion.
type SystemPromptTemplateVersions []*SystemPromptTemplateVersion
