// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/systempromptruntime"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplateversion"
)

// SystemPromptRuntime is the model entity for the SystemPromptRuntime schema.
type SystemPromptRuntime struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// ExposeServerPrompt holds the value of the "expose_server_prompt" field.
	ExposeServerPrompt bool `json:"expose_server_prompt,omitempty"`
	// CompactEnabled holds the value of the "compact_enabled" field.
	CompactEnabled bool `json:"compact_enabled,omitempty"`
	// ActiveTemplateID holds the value of the "active_template_id" field.
	ActiveTemplateID *int64 `json:"active_template_id,omitempty"`
	// ActiveVersionID holds the value of the "active_version_id" field.
	ActiveVersionID *int64 `json:"active_version_id,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int64 `json:"revision,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *int64 `json:"updated_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SystemPromptRuntimeQuery when eager-loading is set.
	Edges        SystemPromptRuntimeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SystemPromptRuntimeEdges holds the relations/edges for other nodes in the graph.
type SystemPromptRuntimeEdges struct {
	// ActiveTemplate holds the value of the active_template edge.
	ActiveTemplate *SystemPromptTemplate `json:"active_template,omitempty"`
	// ActiveVersion holds the value of the active_version edge.
	ActiveVersion *SystemPromptTemplateVersion `json:"active_version,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ActiveTemplateOrErr returns the ActiveTemplate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SystemPromptRuntimeEdges) ActiveTemplateOrErr() (*SystemPromptTemplate, error) {
	if e.ActiveTemplate != nil {
		return e.ActiveTemplate, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: systemprompttemplate.Label}
	}
	return nil, &NotLoadedError{edge: "active_template"}
}

// ActiveVersionOrErr returns the ActiveVersion value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SystemPromptRuntimeEdges) ActiveVersionOrErr() (*SystemPromptTemplateVersion, error) {
	if e.ActiveVersion != nil {
		return e.ActiveVersion, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: systemprompttemplateversion.Label}
	}
	return nil, &NotLoadedError{edge: "active_version"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemPromptRuntime) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systempromptruntime.FieldEnabled, systempromptruntime.FieldExposeServerPrompt, systempromptruntime.FieldCompactEnabled:
			values[i] = new(sql.NullBool)
		case systempromptruntime.FieldID, systempromptruntime.FieldActiveTemplateID, systempromptruntime.FieldActiveVersionID, systempromptruntime.FieldRevision, systempromptruntime.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case systempromptruntime.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemPromptRuntime fields.
func (_m *SystemPromptRuntime) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systempromptruntime.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case systempromptruntime.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case systempromptruntime.FieldExposeServerPrompt:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field expose_server_prompt", values[i])
			} else if value.Valid {
				_m.ExposeServerPrompt = value.Bool
			}
		case systempromptruntime.FieldCompactEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field compact_enabled", values[i])
			} else if value.Valid {
				_m.CompactEnabled = value.Bool
			}
		case systempromptruntime.FieldActiveTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active_template_id", values[i])
			} else if value.Valid {
				_m.ActiveTemplateID = new(int64)
				*_m.ActiveTemplateID = value.Int64
			}
		case systempromptruntime.FieldActiveVersionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active_version_id", values[i])
			} else if value.Valid {
				_m.ActiveVersionID = new(int64)
				*_m.ActiveVersionID = value.Int64
			}
		case systempromptruntime.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case systempromptruntime.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		case systempromptruntime.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SystemPromptRuntime.
// This includes values selected through modifiers, order, etc.
func (_m *SystemPromptRuntime) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActiveTemplate queries the "active_template" edge of the SystemPromptRuntime entity.
func (_m *SystemPromptRuntime) QueryActiveTemplate() *SystemPromptTemplateQuery {
	return NewSystemPromptRuntimeClient(_m.config).QueryActiveTemplate(_m)
}

// QueryActiveVersion queries the "active_version" edge of the SystemPromptRuntime entity.
func (_m *SystemPromptRuntime) QueryActiveVersion() *SystemPromptTemplateVersionQuery {
	return NewSystemPromptRuntimeClient(_m.config).QueryActiveVersion(_m)
}

// Update returns a builder for updating this SystemPromptRuntime.
// Note that you need to call SystemPromptRuntime.Unwrap() before calling this method if this SystemPromptRuntime
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SystemPromptRuntime) Update() *SystemPromptRuntimeUpdateOne {
	return NewSystemPromptRuntimeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SystemPromptRuntime entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SystemPromptRuntime) Unwrap() *SystemPromptRuntime {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemPromptRuntime is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SystemPromptRuntime) String() string {
	var builder strings.Builder
	builder.WriteString("SystemPromptRuntime(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("expose_server_prompt=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExposeServerPrompt))
	builder.WriteString(", ")
	builder.WriteString("compact_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompactEnabled))
	builder.WriteString(", ")
	if v := _m.ActiveTemplateID; v != nil {
		builder.WriteString("active_template_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActiveVersionID; v != nil {
		builder.WriteString("active_version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SystemPromptRuntimes is a parsable slice of SystemPromptRuntime.
type SystemPromptRuntimes []*SystemPromptRuntime
