// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplateversion"
)

// SystemPromptTemplateVersionUpdate is the builder for updating SystemPromptTemplateVersion entities.
type SystemPromptTemplateVersionUpdate struct {
	config
	hooks    []Hook
	mutation *SystemPromptTemplateVersionMutation
}

// Where appends a list predicates to the SystemPromptTemplateVersionUpdate builder.
func (_u *SystemPromptTemplateVersionUpdate) Where(ps ...predicate.SystemPromptTemplateVersion) *SystemPromptTemplateVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *SystemPromptTemplateVersionUpdate) SetTemplateID(v int64) *SystemPromptTemplateVersionUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableTemplateID(v *int64) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SystemPromptTemplateVersionUpdate) SetVersion(v int64) *SystemPromptTemplateVersionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableVersion(v *int64) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SystemPromptTemplateVersionUpdate) AddVersion(v int64) *SystemPromptTemplateVersionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetBody sets the "body" field.
func (_u *SystemPromptTemplateVersionUpdate) SetBody(v string) *SystemPromptTemplateVersionUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableBody(v *string) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *SystemPromptTemplateVersionUpdate) SetSha256(v string) *SystemPromptTemplateVersionUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableSha256(v *string) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetByteLength sets the "byte_length" field.
func (_u *SystemPromptTemplateVersionUpdate) SetByteLength(v int) *SystemPromptTemplateVersionUpdate {
	_u.mutation.ResetByteLength()
	_u.mutation.SetByteLength(v)
	return _u
}

// SetNillableByteLength sets the "byte_length" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableByteLength(v *int) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetByteLength(*v)
	}
	return _u
}

// AddByteLength adds value to the "byte_length" field.
func (_u *SystemPromptTemplateVersionUpdate) AddByteLength(v int) *SystemPromptTemplateVersionUpdate {
	_u.mutation.AddByteLength(v)
	return _u
}

// SetCompositionMode sets the "composition_mode" field.
func (_u *SystemPromptTemplateVersionUpdate) SetCompositionMode(v string) *SystemPromptTemplateVersionUpdate {
	_u.mutation.SetCompositionMode(v)
	return _u
}

// SetNillableCompositionMode sets the "composition_mode" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableCompositionMode(v *string) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetCompositionMode(*v)
	}
	return _u
}

// SetBundleID sets the "bundle_id" field.
func (_u *SystemPromptTemplateVersionUpdate) SetBundleID(v string) *SystemPromptTemplateVersionUpdate {
	_u.mutation.SetBundleID(v)
	return _u
}

// SetNillableBundleID sets the "bundle_id" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableBundleID(v *string) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetBundleID(*v)
	}
	return _u
}

// ClearBundleID clears the value of the "bundle_id" field.
func (_u *SystemPromptTemplateVersionUpdate) ClearBundleID() *SystemPromptTemplateVersionUpdate {
	_u.mutation.ClearBundleID()
	return _u
}

// SetBundleManifestSha256 sets the "bundle_manifest_sha256" field.
func (_u *SystemPromptTemplateVersionUpdate) SetBundleManifestSha256(v string) *SystemPromptTemplateVersionUpdate {
	_u.mutation.SetBundleManifestSha256(v)
	return _u
}

// SetNillableBundleManifestSha256 sets the "bundle_manifest_sha256" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableBundleManifestSha256(v *string) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetBundleManifestSha256(*v)
	}
	return _u
}

// ClearBundleManifestSha256 clears the value of the "bundle_manifest_sha256" field.
func (_u *SystemPromptTemplateVersionUpdate) ClearBundleManifestSha256() *SystemPromptTemplateVersionUpdate {
	_u.mutation.ClearBundleManifestSha256()
	return _u
}

// SetNote sets the "note" field.
func (_u *SystemPromptTemplateVersionUpdate) SetNote(v string) *SystemPromptTemplateVersionUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableNote(v *string) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SystemPromptTemplateVersionUpdate) SetCreatedBy(v int64) *SystemPromptTemplateVersionUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillableCreatedBy(v *int64) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SystemPromptTemplateVersionUpdate) AddCreatedBy(v int64) *SystemPromptTemplateVersionUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SystemPromptTemplateVersionUpdate) ClearCreatedBy() *SystemPromptTemplateVersionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *SystemPromptTemplateVersionUpdate) SetPublishedAt(v time.Time) *SystemPromptTemplateVersionUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillablePublishedAt(v *time.Time) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *SystemPromptTemplateVersionUpdate) ClearPublishedAt() *SystemPromptTemplateVersionUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetPublishedBy sets the "published_by" field.
func (_u *SystemPromptTemplateVersionUpdate) SetPublishedBy(v int64) *SystemPromptTemplateVersionUpdate {
	_u.mutation.ResetPublishedBy()
	_u.mutation.SetPublishedBy(v)
	return _u
}

// SetNillablePublishedBy sets the "published_by" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdate) SetNillablePublishedBy(v *int64) *SystemPromptTemplateVersionUpdate {
	if v != nil {
		_u.SetPublishedBy(*v)
	}
	return _u
}

// AddPublishedBy adds value to the "published_by" field.
func (_u *SystemPromptTemplateVersionUpdate) AddPublishedBy(v int64) *SystemPromptTemplateVersionUpdate {
	_u.mutation.AddPublishedBy(v)
	return _u
}

// ClearPublishedBy clears the value of the "published_by" field.
func (_u *SystemPromptTemplateVersionUpdate) ClearPublishedBy() *SystemPromptTemplateVersionUpdate {
	_u.mutation.ClearPublishedBy()
	return _u
}

// SetTemplate sets the "template" edge to the SystemPromptTemplate entity.
func (_u *SystemPromptTemplateVersionUpdate) SetTemplate(v *SystemPromptTemplate) *SystemPromptTemplateVersionUpdate {
	return _u.SetTemplateID(v.ID)
}

// Mutation returns the SystemPromptTemplateVersionMutation object of the builder.
func (_u *SystemPromptTemplateVersionUpdate) Mutation() *SystemPromptTemplateVersionMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the SystemPromptTemplate entity.
func (_u *SystemPromptTemplateVersionUpdate) ClearTemplate() *SystemPromptTemplateVersionUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemPromptTemplateVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemPromptTemplateVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemPromptTemplateVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemPromptTemplateVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemPromptTemplateVersionUpdate) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := systemprompttemplateversion.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := systemprompttemplateversion.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ByteLength(); ok {
		if err := systemprompttemplateversion.ByteLengthValidator(v); err != nil {
			return &ValidationError{Name: "byte_length", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.byte_length": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompositionMode(); ok {
		if err := systemprompttemplateversion.CompositionModeValidator(v); err != nil {
			return &ValidationError{Name: "composition_mode", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.composition_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BundleID(); ok {
		if err := systemprompttemplateversion.BundleIDValidator(v); err != nil {
			return &ValidationError{Name: "bundle_id", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.bundle_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BundleManifestSha256(); ok {
		if err := systemprompttemplateversion.BundleManifestSha256Validator(v); err != nil {
			return &ValidationError{Name: "bundle_manifest_sha256", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.bundle_manifest_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := systemprompttemplateversion.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.note": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemPromptTemplateVersion.template"`)
	}
	return nil
}

func (_u *SystemPromptTemplateVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemprompttemplateversion.Table, systemprompttemplateversion.Columns, sqlgraph.NewFieldSpec(systemprompttemplateversion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(systemprompttemplateversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(systemprompttemplateversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(systemprompttemplateversion.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(systemprompttemplateversion.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteLength(); ok {
		_spec.SetField(systemprompttemplateversion.FieldByteLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedByteLength(); ok {
		_spec.AddField(systemprompttemplateversion.FieldByteLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompositionMode(); ok {
		_spec.SetField(systemprompttemplateversion.FieldCompositionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.BundleID(); ok {
		_spec.SetField(systemprompttemplateversion.FieldBundleID, field.TypeString, value)
	}
	if _u.mutation.BundleIDCleared() {
		_spec.ClearField(systemprompttemplateversion.FieldBundleID, field.TypeString)
	}
	if value, ok := _u.mutation.BundleManifestSha256(); ok {
		_spec.SetField(systemprompttemplateversion.FieldBundleManifestSha256, field.TypeString, value)
	}
	if _u.mutation.BundleManifestSha256Cleared() {
		_spec.ClearField(systemprompttemplateversion.FieldBundleManifestSha256, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(systemprompttemplateversion.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(systemprompttemplateversion.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(systemprompttemplateversion.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(systemprompttemplateversion.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(systemprompttemplateversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(systemprompttemplateversion.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedBy(); ok {
		_spec.SetField(systemprompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPublishedBy(); ok {
		_spec.AddField(systemprompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
	}
	if _u.mutation.PublishedByCleared() {
		_spec.ClearField(systemprompttemplateversion.FieldPublishedBy, field.TypeInt64)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemprompttemplateversion.TemplateTable,
			Columns: []string{systemprompttemplateversion.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemprompttemplateversion.TemplateTable,
			Columns: []string{systemprompttemplateversion.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemprompttemplateversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemPromptTemplateVersionUpdateOne is the builder for updating a single SystemPromptTemplateVersion entity.
type SystemPromptTemplateVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemPromptTemplateVersionMutation
}

// SetTemplateID sets the "template_id" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetTemplateID(v int64) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableTemplateID(v *int64) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetVersion(v int64) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableVersion(v *int64) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SystemPromptTemplateVersionUpdateOne) AddVersion(v int64) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetBody sets the "body" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetBody(v string) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableBody(v *string) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetSha256(v string) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableSha256(v *string) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetByteLength sets the "byte_length" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetByteLength(v int) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ResetByteLength()
	_u.mutation.SetByteLength(v)
	return _u
}

// SetNillableByteLength sets the "byte_length" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableByteLength(v *int) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetByteLength(*v)
	}
	return _u
}

// AddByteLength adds value to the "byte_length" field.
func (_u *SystemPromptTemplateVersionUpdateOne) AddByteLength(v int) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.AddByteLength(v)
	return _u
}

// SetCompositionMode sets the "composition_mode" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetCompositionMode(v string) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.SetCompositionMode(v)
	return _u
}

// SetNillableCompositionMode sets the "composition_mode" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableCompositionMode(v *string) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetCompositionMode(*v)
	}
	return _u
}

// SetBundleID sets the "bundle_id" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetBundleID(v string) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.SetBundleID(v)
	return _u
}

// SetNillableBundleID sets the "bundle_id" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableBundleID(v *string) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetBundleID(*v)
	}
	return _u
}

// ClearBundleID clears the value of the "bundle_id" field.
func (_u *SystemPromptTemplateVersionUpdateOne) ClearBundleID() *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ClearBundleID()
	return _u
}

// SetBundleManifestSha256 sets the "bundle_manifest_sha256" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetBundleManifestSha256(v string) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.SetBundleManifestSha256(v)
	return _u
}

// SetNillableBundleManifestSha256 sets the "bundle_manifest_sha256" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableBundleManifestSha256(v *string) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetBundleManifestSha256(*v)
	}
	return _u
}

// ClearBundleManifestSha256 clears the value of the "bundle_manifest_sha256" field.
func (_u *SystemPromptTemplateVersionUpdateOne) ClearBundleManifestSha256() *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ClearBundleManifestSha256()
	return _u
}

// SetNote sets the "note" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNote(v string) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableNote(v *string) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetCreatedBy(v int64) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillableCreatedBy(v *int64) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SystemPromptTemplateVersionUpdateOne) AddCreatedBy(v int64) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SystemPromptTemplateVersionUpdateOne) ClearCreatedBy() *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetPublishedAt(v time.Time) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillablePublishedAt(v *time.Time) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *SystemPromptTemplateVersionUpdateOne) ClearPublishedAt() *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetPublishedBy sets the "published_by" field.
func (_u *SystemPromptTemplateVersionUpdateOne) SetPublishedBy(v int64) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ResetPublishedBy()
	_u.mutation.SetPublishedBy(v)
	return _u
}

// SetNillablePublishedBy sets the "published_by" field if the given value is not nil.
func (_u *SystemPromptTemplateVersionUpdateOne) SetNillablePublishedBy(v *int64) *SystemPromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetPublishedBy(*v)
	}
	return _u
}

// AddPublishedBy adds value to the "published_by" field.
func (_u *SystemPromptTemplateVersionUpdateOne) AddPublishedBy(v int64) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.AddPublishedBy(v)
	return _u
}

// ClearPublishedBy clears the value of the "published_by" field.
func (_u *SystemPromptTemplateVersionUpdateOne) ClearPublishedBy() *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ClearPublishedBy()
	return _u
}

// SetTemplate sets the "template" edge to the SystemPromptTemplate entity.
func (_u *SystemPromptTemplateVersionUpdateOne) SetTemplate(v *SystemPromptTemplate) *SystemPromptTemplateVersionUpdateOne {
	return _u.SetTemplateID(v.ID)
}

// Mutation returns the SystemPromptTemplateVersionMutation object of the builder.
func (_u *SystemPromptTemplateVersionUpdateOne) Mutation() *SystemPromptTemplateVersionMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the SystemPromptTemplate entity.
func (_u *SystemPromptTemplateVersionUpdateOne) ClearTemplate() *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// Where appends a list predicates to the SystemPromptTemplateVersionUpdate builder.
func (_u *SystemPromptTemplateVersionUpdateOne) Where(ps ...predicate.SystemPromptTemplateVersion) *SystemPromptTemplateVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemPromptTemplateVersionUpdateOne) Select(field string, fields ...string) *SystemPromptTemplateVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemPromptTemplateVersion entity.
func (_u *SystemPromptTemplateVersionUpdateOne) Save(ctx context.Context) (*SystemPromptTemplateVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemPromptTemplateVersionUpdateOne) SaveX(ctx context.Context) *SystemPromptTemplateVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemPromptTemplateVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemPromptTemplateVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemPromptTemplateVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := systemprompttemplateversion.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := systemprompttemplateversion.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ByteLength(); ok {
		if err := systemprompttemplateversion.ByteLengthValidator(v); err != nil {
			return &ValidationError{Name: "byte_length", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.byte_length": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompositionMode(); ok {
		if err := systemprompttemplateversion.CompositionModeValidator(v); err != nil {
			return &ValidationError{Name: "composition_mode", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.composition_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BundleID(); ok {
		if err := systemprompttemplateversion.BundleIDValidator(v); err != nil {
			return &ValidationError{Name: "bundle_id", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.bundle_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BundleManifestSha256(); ok {
		if err := systemprompttemplateversion.BundleManifestSha256Validator(v); err != nil {
			return &ValidationError{Name: "bundle_manifest_sha256", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.bundle_manifest_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := systemprompttemplateversion.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplateVersion.note": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemPromptTemplateVersion.template"`)
	}
	return nil
}

func (_u *SystemPromptTemplateVersionUpdateOne) sqlSave(ctx context.Context) (_node *SystemPromptTemplateVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemprompttemplateversion.Table, systemprompttemplateversion.Columns, sqlgraph.NewFieldSpec(systemprompttemplateversion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemPromptTemplateVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemprompttemplateversion.FieldID)
		for _, f := range fields {
			if !systemprompttemplateversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemprompttemplateversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(systemprompttemplateversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(systemprompttemplateversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(systemprompttemplateversion.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(systemprompttemplateversion.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteLength(); ok {
		_spec.SetField(systemprompttemplateversion.FieldByteLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedByteLength(); ok {
		_spec.AddField(systemprompttemplateversion.FieldByteLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompositionMode(); ok {
		_spec.SetField(systemprompttemplateversion.FieldCompositionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.BundleID(); ok {
		_spec.SetField(systemprompttemplateversion.FieldBundleID, field.TypeString, value)
	}
	if _u.mutation.BundleIDCleared() {
		_spec.ClearField(systemprompttemplateversion.FieldBundleID, field.TypeString)
	}
	if value, ok := _u.mutation.BundleManifestSha256(); ok {
		_spec.SetField(systemprompttemplateversion.FieldBundleManifestSha256, field.TypeString, value)
	}
	if _u.mutation.BundleManifestSha256Cleared() {
		_spec.ClearField(systemprompttemplateversion.FieldBundleManifestSha256, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(systemprompttemplateversion.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(systemprompttemplateversion.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(systemprompttemplateversion.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(systemprompttemplateversion.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(systemprompttemplateversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(systemprompttemplateversion.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedBy(); ok {
		_spec.SetField(systemprompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPublishedBy(); ok {
		_spec.AddField(systemprompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
	}
	if _u.mutation.PublishedByCleared() {
		_spec.ClearField(systemprompttemplateversion.FieldPublishedBy, field.TypeInt64)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemprompttemplateversion.TemplateTable,
			Columns: []string{systemprompttemplateversion.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   systemprompttemplateversion.TemplateTable,
			Columns: []string{systemprompttemplateversion.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SystemPromptTemplateVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemprompttemplateversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
