// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplateversion"
)

// SystemPromptTemplateQuery is the builder for querying SystemPromptTemplate entities.
type SystemPromptTemplateQuery struct {
	config
	ctx          *QueryContext
	order        []systemprompttemplate.OrderOption
	inters       []Interceptor
	predicates   []predicate.SystemPromptTemplate
	withVersions *SystemPromptTemplateVersionQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SystemPromptTemplateQuery builder.
func (_q *SystemPromptTemplateQuery) Where(ps ...predicate.SystemPromptTemplate) *SystemPromptTemplateQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SystemPromptTemplateQuery) Limit(limit int) *SystemPromptTemplateQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SystemPromptTemplateQuery) Offset(offset int) *SystemPromptTemplateQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SystemPromptTemplateQuery) Unique(unique bool) *SystemPromptTemplateQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SystemPromptTemplateQuery) Order(o ...systemprompttemplate.OrderOption) *SystemPromptTemplateQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryVersions chains the current query on the "versions" edge.
func (_q *SystemPromptTemplateQuery) QueryVersions() *SystemPromptTemplateVersionQuery {
	query := (&SystemPromptTemplateVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(systemprompttemplate.Table, systemprompttemplate.FieldID, selector),
			sqlgraph.To(systemprompttemplateversion.Table, systemprompttemplateversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, systemprompttemplate.VersionsTable, systemprompttemplate.VersionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SystemPromptTemplate entity from the query.
// Returns a *NotFoundError when no SystemPromptTemplate was found.
func (_q *SystemPromptTemplateQuery) First(ctx context.Context) (*SystemPromptTemplate, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{systemprompttemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SystemPromptTemplateQuery) FirstX(ctx context.Context) *SystemPromptTemplate {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SystemPromptTemplate ID from the query.
// Returns a *NotFoundError when no SystemPromptTemplate ID was found.
func (_q *SystemPromptTemplateQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{systemprompttemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SystemPromptTemplateQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SystemPromptTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SystemPromptTemplate entity is found.
// Returns a *NotFoundError when no SystemPromptTemplate entities are found.
func (_q *SystemPromptTemplateQuery) Only(ctx context.Context) (*SystemPromptTemplate, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{systemprompttemplate.Label}
	default:
		return nil, &NotSingularError{systemprompttemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SystemPromptTemplateQuery) OnlyX(ctx context.Context) *SystemPromptTemplate {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SystemPromptTemplate ID in the query.
// Returns a *NotSingularError when more than one SystemPromptTemplate ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SystemPromptTemplateQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{systemprompttemplate.Label}
	default:
		err = &NotSingularError{systemprompttemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SystemPromptTemplateQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SystemPromptTemplates.
func (_q *SystemPromptTemplateQuery) All(ctx context.Context) ([]*SystemPromptTemplate, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SystemPromptTemplate, *SystemPromptTemplateQuery]()
	return withInterceptors[[]*SystemPromptTemplate](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SystemPromptTemplateQuery) AllX(ctx context.Context) []*SystemPromptTemplate {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SystemPromptTemplate IDs.
func (_q *SystemPromptTemplateQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(systemprompttemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SystemPromptTemplateQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SystemPromptTemplateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SystemPromptTemplateQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SystemPromptTemplateQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SystemPromptTemplateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SystemPromptTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SystemPromptTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SystemPromptTemplateQuery) Clone() *SystemPromptTemplateQuery {
	if _q == nil {
		return nil
	}
	return &SystemPromptTemplateQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]systemprompttemplate.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.SystemPromptTemplate{}, _q.predicates...),
		withVersions: _q.withVersions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithVersions tells the query-builder to eager-load the nodes that are connected to
// the "versions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SystemPromptTemplateQuery) WithVersions(opts ...func(*SystemPromptTemplateVersionQuery)) *SystemPromptTemplateQuery {
	query := (&SystemPromptTemplateVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVersions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SystemPromptTemplate.Query().
//		GroupBy(systemprompttemplate.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SystemPromptTemplateQuery) GroupBy(field string, fields ...string) *SystemPromptTemplateGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SystemPromptTemplateGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = systemprompttemplate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SystemPromptTemplate.Query().
//		Select(systemprompttemplate.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SystemPromptTemplateQuery) Select(fields ...string) *SystemPromptTemplateSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SystemPromptTemplateSelect{SystemPromptTemplateQuery: _q}
	sbuild.label = systemprompttemplate.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SystemPromptTemplateSelect configured with the given aggregations.
func (_q *SystemPromptTemplateQuery) Aggregate(fns ...AggregateFunc) *SystemPromptTemplateSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SystemPromptTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !systemprompttemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SystemPromptTemplateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SystemPromptTemplate, error) {
	var (
		nodes       = []*SystemPromptTemplate{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withVersions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SystemPromptTemplate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SystemPromptTemplate{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withVersions; query != nil {
		if err := _q.loadVersions(ctx, query, nodes,
			func(n *SystemPromptTemplate) { n.Edges.Versions = []*SystemPromptTemplateVersion{} },
			func(n *SystemPromptTemplate, e *SystemPromptTemplateVersion) {
				n.Edges.Versions = append(n.Edges.Versions, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SystemPromptTemplateQuery) loadVersions(ctx context.Context, query *SystemPromptTemplateVersionQuery, nodes []*SystemPromptTemplate, init func(*SystemPromptTemplate), assign func(*SystemPromptTemplate, *SystemPromptTemplateVersion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SystemPromptTemplate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(systemprompttemplateversion.FieldTemplateID)
	}
	query.Where(predicate.SystemPromptTemplateVersion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(systemprompttemplate.VersionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TemplateID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "template_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SystemPromptTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SystemPromptTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(systemprompttemplate.Table, systemprompttemplate.Columns, sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemprompttemplate.FieldID)
		for i := range fields {
			if fields[i] != systemprompttemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SystemPromptTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(systemprompttemplate.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = systemprompttemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SystemPromptTemplateQuery) ForUpdate(opts ...sql.LockOption) *SystemPromptTemplateQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SystemPromptTemplateQuery) ForShare(opts ...sql.LockOption) *SystemPromptTemplateQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SystemPromptTemplateGroupBy is the group-by builder for SystemPromptTemplate entities.
type SystemPromptTemplateGroupBy struct {
	selector
	build *SystemPromptTemplateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SystemPromptTemplateGroupBy) Aggregate(fns ...AggregateFunc) *SystemPromptTemplateGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SystemPromptTemplateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SystemPromptTemplateQuery, *SystemPromptTemplateGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SystemPromptTemplateGroupBy) sqlScan(ctx context.Context, root *SystemPromptTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SystemPromptTemplateSelect is the builder for selecting fields of SystemPromptTemplate entities.
type SystemPromptTemplateSelect struct {
	*SystemPromptTemplateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SystemPromptTemplateSelect) Aggregate(fns ...AggregateFunc) *SystemPromptTemplateSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SystemPromptTemplateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SystemPromptTemplateQuery, *SystemPromptTemplateSelect](ctx, _s.SystemPromptTemplateQuery, _s, _s.inters, v)
}

func (_s *SystemPromptTemplateSelect) sqlScan(ctx context.Context, root *SystemPromptTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
