// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplateversion"
)

// SystemPromptTemplateCreate is the builder for creating a SystemPromptTemplate entity.
type SystemPromptTemplateCreate struct {
	config
	mutation *SystemPromptTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SystemPromptTemplateCreate) SetCreatedAt(v time.Time) *SystemPromptTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SystemPromptTemplateCreate) SetNillableCreatedAt(v *time.Time) *SystemPromptTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SystemPromptTemplateCreate) SetUpdatedAt(v time.Time) *SystemPromptTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SystemPromptTemplateCreate) SetNillableUpdatedAt(v *time.Time) *SystemPromptTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SystemPromptTemplateCreate) SetDeletedAt(v time.Time) *SystemPromptTemplateCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SystemPromptTemplateCreate) SetNillableDeletedAt(v *time.Time) *SystemPromptTemplateCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *SystemPromptTemplateCreate) SetSlug(v string) *SystemPromptTemplateCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SystemPromptTemplateCreate) SetName(v string) *SystemPromptTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SystemPromptTemplateCreate) SetDescription(v string) *SystemPromptTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SystemPromptTemplateCreate) SetNillableDescription(v *string) *SystemPromptTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsSeed sets the "is_seed" field.
func (_c *SystemPromptTemplateCreate) SetIsSeed(v bool) *SystemPromptTemplateCreate {
	_c.mutation.SetIsSeed(v)
	return _c
}

// SetNillableIsSeed sets the "is_seed" field if the given value is not nil.
func (_c *SystemPromptTemplateCreate) SetNillableIsSeed(v *bool) *SystemPromptTemplateCreate {
	if v != nil {
		_c.SetIsSeed(*v)
	}
	return _c
}

// SetManagedSource sets the "managed_source" field.
func (_c *SystemPromptTemplateCreate) SetManagedSource(v string) *SystemPromptTemplateCreate {
	_c.mutation.SetManagedSource(v)
	return _c
}

// SetNillableManagedSource sets the "managed_source" field if the given value is not nil.
func (_c *SystemPromptTemplateCreate) SetNillableManagedSource(v *string) *SystemPromptTemplateCreate {
	if v != nil {
		_c.SetManagedSource(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SystemPromptTemplateCreate) SetCreatedBy(v int64) *SystemPromptTemplateCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SystemPromptTemplateCreate) SetNillableCreatedBy(v *int64) *SystemPromptTemplateCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SystemPromptTemplateCreate) SetUpdatedBy(v int64) *SystemPromptTemplateCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SystemPromptTemplateCreate) SetNillableUpdatedBy(v *int64) *SystemPromptTemplateCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// AddVersionIDs adds the "versions" edge to the SystemPromptTemplateVersion entity by IDs.
func (_c *SystemPromptTemplateCreate) AddVersionIDs(ids ...int64) *SystemPromptTemplateCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the SystemPromptTemplateVersion entity.
func (_c *SystemPromptTemplateCreate) AddVersions(v ...*SystemPromptTemplateVersion) *SystemPromptTemplateCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// Mutation returns the SystemPromptTemplateMutation object of the builder.
func (_c *SystemPromptTemplateCreate) Mutation() *SystemPromptTemplateMutation {
	return _c.mutation
}

// Save creates the SystemPromptTemplate in the database.
func (_c *SystemPromptTemplateCreate) Save(ctx context.Context) (*SystemPromptTemplate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemPromptTemplateCreate) SaveX(ctx context.Context) *SystemPromptTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemPromptTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemPromptTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemPromptTemplateCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if systemprompttemplate.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemprompttemplate.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := systemprompttemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if systemprompttemplate.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemprompttemplate.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := systemprompttemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := systemprompttemplate.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.IsSeed(); !ok {
		v := systemprompttemplate.DefaultIsSeed
		_c.mutation.SetIsSeed(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemPromptTemplateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SystemPromptTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemPromptTemplate.updated_at"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "SystemPromptTemplate.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := systemprompttemplate.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplate.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SystemPromptTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := systemprompttemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "SystemPromptTemplate.description"`)}
	}
	if _, ok := _c.mutation.IsSeed(); !ok {
		return &ValidationError{Name: "is_seed", err: errors.New(`ent: missing required field "SystemPromptTemplate.is_seed"`)}
	}
	if v, ok := _c.mutation.ManagedSource(); ok {
		if err := systemprompttemplate.ManagedSourceValidator(v); err != nil {
			return &ValidationError{Name: "managed_source", err: fmt.Errorf(`ent: validator failed for field "SystemPromptTemplate.managed_source": %w`, err)}
		}
	}
	return nil
}

func (_c *SystemPromptTemplateCreate) sqlSave(ctx context.Context) (*SystemPromptTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemPromptTemplateCreate) createSpec() (*SystemPromptTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemPromptTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(systemprompttemplate.Table, sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(systemprompttemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(systemprompttemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(systemprompttemplate.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(systemprompttemplate.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(systemprompttemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(systemprompttemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsSeed(); ok {
		_spec.SetField(systemprompttemplate.FieldIsSeed, field.TypeBool, value)
		_node.IsSeed = value
	}
	if value, ok := _c.mutation.ManagedSource(); ok {
		_spec.SetField(systemprompttemplate.FieldManagedSource, field.TypeString, value)
		_node.ManagedSource = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(systemprompttemplate.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(systemprompttemplate.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   systemprompttemplate.VersionsTable,
			Columns: []string{systemprompttemplate.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplateversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemPromptTemplate.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemPromptTemplateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemPromptTemplateCreate) OnConflict(opts ...sql.ConflictOption) *SystemPromptTemplateUpsertOne {
	_c.conflict = opts
	return &SystemPromptTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemPromptTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemPromptTemplateCreate) OnConflictColumns(columns ...string) *SystemPromptTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemPromptTemplateUpsertOne{
		create: _c,
	}
}

type (
	// SystemPromptTemplateUpsertOne is the builder for "upsert"-ing
	//  one SystemPromptTemplate node.
	SystemPromptTemplateUpsertOne struct {
		create *SystemPromptTemplateCreate
	}

	// SystemPromptTemplateUpsert is the "OnConflict" setter.
	SystemPromptTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemPromptTemplateUpsert) SetUpdatedAt(v time.Time) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateUpdatedAt() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SystemPromptTemplateUpsert) SetDeletedAt(v time.Time) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateDeletedAt() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SystemPromptTemplateUpsert) ClearDeletedAt() *SystemPromptTemplateUpsert {
	u.SetNull(systemprompttemplate.FieldDeletedAt)
	return u
}

// SetSlug sets the "slug" field.
func (u *SystemPromptTemplateUpsert) SetSlug(v string) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateSlug() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldSlug)
	return u
}

// SetName sets the "name" field.
func (u *SystemPromptTemplateUpsert) SetName(v string) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateName() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SystemPromptTemplateUpsert) SetDescription(v string) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateDescription() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldDescription)
	return u
}

// SetIsSeed sets the "is_seed" field.
func (u *SystemPromptTemplateUpsert) SetIsSeed(v bool) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldIsSeed, v)
	return u
}

// UpdateIsSeed sets the "is_seed" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateIsSeed() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldIsSeed)
	return u
}

// SetManagedSource sets the "managed_source" field.
func (u *SystemPromptTemplateUpsert) SetManagedSource(v string) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldManagedSource, v)
	return u
}

// UpdateManagedSource sets the "managed_source" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateManagedSource() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldManagedSource)
	return u
}

// ClearManagedSource clears the value of the "managed_source" field.
func (u *SystemPromptTemplateUpsert) ClearManagedSource() *SystemPromptTemplateUpsert {
	u.SetNull(systemprompttemplate.FieldManagedSource)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *SystemPromptTemplateUpsert) SetCreatedBy(v int64) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateCreatedBy() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *SystemPromptTemplateUpsert) AddCreatedBy(v int64) *SystemPromptTemplateUpsert {
	u.Add(systemprompttemplate.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SystemPromptTemplateUpsert) ClearCreatedBy() *SystemPromptTemplateUpsert {
	u.SetNull(systemprompttemplate.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SystemPromptTemplateUpsert) SetUpdatedBy(v int64) *SystemPromptTemplateUpsert {
	u.Set(systemprompttemplate.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsert) UpdateUpdatedBy() *SystemPromptTemplateUpsert {
	u.SetExcluded(systemprompttemplate.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *SystemPromptTemplateUpsert) AddUpdatedBy(v int64) *SystemPromptTemplateUpsert {
	u.Add(systemprompttemplate.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SystemPromptTemplateUpsert) ClearUpdatedBy() *SystemPromptTemplateUpsert {
	u.SetNull(systemprompttemplate.FieldUpdatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SystemPromptTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SystemPromptTemplateUpsertOne) UpdateNewValues() *SystemPromptTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(systemprompttemplate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemPromptTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SystemPromptTemplateUpsertOne) Ignore() *SystemPromptTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemPromptTemplateUpsertOne) DoNothing() *SystemPromptTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemPromptTemplateCreate.OnConflict
// documentation for more info.
func (u *SystemPromptTemplateUpsertOne) Update(set func(*SystemPromptTemplateUpsert)) *SystemPromptTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemPromptTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemPromptTemplateUpsertOne) SetUpdatedAt(v time.Time) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateUpdatedAt() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SystemPromptTemplateUpsertOne) SetDeletedAt(v time.Time) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateDeletedAt() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SystemPromptTemplateUpsertOne) ClearDeletedAt() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.ClearDeletedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *SystemPromptTemplateUpsertOne) SetSlug(v string) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateSlug() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *SystemPromptTemplateUpsertOne) SetName(v string) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateName() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SystemPromptTemplateUpsertOne) SetDescription(v string) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateDescription() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateDescription()
	})
}

// SetIsSeed sets the "is_seed" field.
func (u *SystemPromptTemplateUpsertOne) SetIsSeed(v bool) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetIsSeed(v)
	})
}

// UpdateIsSeed sets the "is_seed" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateIsSeed() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateIsSeed()
	})
}

// SetManagedSource sets the "managed_source" field.
func (u *SystemPromptTemplateUpsertOne) SetManagedSource(v string) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetManagedSource(v)
	})
}

// UpdateManagedSource sets the "managed_source" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateManagedSource() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateManagedSource()
	})
}

// ClearManagedSource clears the value of the "managed_source" field.
func (u *SystemPromptTemplateUpsertOne) ClearManagedSource() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.ClearManagedSource()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SystemPromptTemplateUpsertOne) SetCreatedBy(v int64) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *SystemPromptTemplateUpsertOne) AddCreatedBy(v int64) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateCreatedBy() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SystemPromptTemplateUpsertOne) ClearCreatedBy() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SystemPromptTemplateUpsertOne) SetUpdatedBy(v int64) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *SystemPromptTemplateUpsertOne) AddUpdatedBy(v int64) *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertOne) UpdateUpdatedBy() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SystemPromptTemplateUpsertOne) ClearUpdatedBy() *SystemPromptTemplateUpsertOne {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *SystemPromptTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemPromptTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemPromptTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SystemPromptTemplateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SystemPromptTemplateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SystemPromptTemplateCreateBulk is the builder for creating many SystemPromptTemplate entities in bulk.
type SystemPromptTemplateCreateBulk struct {
	config
	err      error
	builders []*SystemPromptTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the SystemPromptTemplate entities in the database.
func (_c *SystemPromptTemplateCreateBulk) Save(ctx context.Context) ([]*SystemPromptTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SystemPromptTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemPromptTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemPromptTemplateCreateBulk) SaveX(ctx context.Context) []*SystemPromptTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemPromptTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemPromptTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemPromptTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemPromptTemplateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemPromptTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *SystemPromptTemplateUpsertBulk {
	_c.conflict = opts
	return &SystemPromptTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemPromptTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemPromptTemplateCreateBulk) OnConflictColumns(columns ...string) *SystemPromptTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemPromptTemplateUpsertBulk{
		create: _c,
	}
}

// SystemPromptTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of SystemPromptTemplate nodes.
type SystemPromptTemplateUpsertBulk struct {
	create *SystemPromptTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SystemPromptTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SystemPromptTemplateUpsertBulk) UpdateNewValues() *SystemPromptTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(systemprompttemplate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemPromptTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SystemPromptTemplateUpsertBulk) Ignore() *SystemPromptTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemPromptTemplateUpsertBulk) DoNothing() *SystemPromptTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemPromptTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *SystemPromptTemplateUpsertBulk) Update(set func(*SystemPromptTemplateUpsert)) *SystemPromptTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemPromptTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemPromptTemplateUpsertBulk) SetUpdatedAt(v time.Time) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateUpdatedAt() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SystemPromptTemplateUpsertBulk) SetDeletedAt(v time.Time) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateDeletedAt() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SystemPromptTemplateUpsertBulk) ClearDeletedAt() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.ClearDeletedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *SystemPromptTemplateUpsertBulk) SetSlug(v string) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateSlug() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *SystemPromptTemplateUpsertBulk) SetName(v string) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateName() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SystemPromptTemplateUpsertBulk) SetDescription(v string) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateDescription() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateDescription()
	})
}

// SetIsSeed sets the "is_seed" field.
func (u *SystemPromptTemplateUpsertBulk) SetIsSeed(v bool) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetIsSeed(v)
	})
}

// UpdateIsSeed sets the "is_seed" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateIsSeed() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateIsSeed()
	})
}

// SetManagedSource sets the "managed_source" field.
func (u *SystemPromptTemplateUpsertBulk) SetManagedSource(v string) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetManagedSource(v)
	})
}

// UpdateManagedSource sets the "managed_source" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateManagedSource() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateManagedSource()
	})
}

// ClearManagedSource clears the value of the "managed_source" field.
func (u *SystemPromptTemplateUpsertBulk) ClearManagedSource() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.ClearManagedSource()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SystemPromptTemplateUpsertBulk) SetCreatedBy(v int64) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *SystemPromptTemplateUpsertBulk) AddCreatedBy(v int64) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateCreatedBy() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SystemPromptTemplateUpsertBulk) ClearCreatedBy() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SystemPromptTemplateUpsertBulk) SetUpdatedBy(v int64) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *SystemPromptTemplateUpsertBulk) AddUpdatedBy(v int64) *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SystemPromptTemplateUpsertBulk) UpdateUpdatedBy() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SystemPromptTemplateUpsertBulk) ClearUpdatedBy() *SystemPromptTemplateUpsertBulk {
	return u.Update(func(s *SystemPromptTemplateUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *SystemPromptTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SystemPromptTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemPromptTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemPromptTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
