// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplate"
)

// SystemPromptTemplate is the model entity for the SystemPromptTemplate schema.
type SystemPromptTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// IsSeed holds the value of the "is_seed" field.
	IsSeed bool `json:"is_seed,omitempty"`
	// ManagedSource holds the value of the "managed_source" field.
	ManagedSource *string `json:"managed_source,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *int64 `json:"updated_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SystemPromptTemplateQuery when eager-loading is set.
	Edges        SystemPromptTemplateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SystemPromptTemplateEdges holds the relations/edges for other nodes in the graph.
type SystemPromptTemplateEdges struct {
	// Versions holds the value of the versions edge.
	Versions []*SystemPromptTemplateVersion `json:"versions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VersionsOrErr returns the Versions value or an error if the edge
// was not loaded in eager-loading.
func (e SystemPromptTemplateEdges) VersionsOrErr() ([]*SystemPromptTemplateVersion, error) {
	if e.loadedTypes[0] {
		return e.Versions, nil
	}
	return nil, &NotLoadedError{edge: "versions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemPromptTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systemprompttemplate.FieldIsSeed:
			values[i] = new(sql.NullBool)
		case systemprompttemplate.FieldID, systemprompttemplate.FieldCreatedBy, systemprompttemplate.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case systemprompttemplate.FieldSlug, systemprompttemplate.FieldName, systemprompttemplate.FieldDescription, systemprompttemplate.FieldManagedSource:
			values[i] = new(sql.NullString)
		case systemprompttemplate.FieldCreatedAt, systemprompttemplate.FieldUpdatedAt, systemprompttemplate.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemPromptTemplate fields.
func (_m *SystemPromptTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systemprompttemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case systemprompttemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case systemprompttemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case systemprompttemplate.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case systemprompttemplate.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case systemprompttemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case systemprompttemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case systemprompttemplate.FieldIsSeed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_seed", values[i])
			} else if value.Valid {
				_m.IsSeed = value.Bool
			}
		case systemprompttemplate.FieldManagedSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field managed_source", values[i])
			} else if value.Valid {
				_m.ManagedSource = new(string)
				*_m.ManagedSource = value.String
			}
		case systemprompttemplate.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case systemprompttemplate.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SystemPromptTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *SystemPromptTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVersions queries the "versions" edge of the SystemPromptTemplate entity.
func (_m *SystemPromptTemplate) QueryVersions() *SystemPromptTemplateVersionQuery {
	return NewSystemPromptTemplateClient(_m.config).QueryVersions(_m)
}

// Update returns a builder for updating this SystemPromptTemplate.
// Note that you need to call SystemPromptTemplate.Unwrap() before calling this method if this SystemPromptTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SystemPromptTemplate) Update() *SystemPromptTemplateUpdateOne {
	return NewSystemPromptTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SystemPromptTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SystemPromptTemplate) Unwrap() *SystemPromptTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemPromptTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SystemPromptTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("SystemPromptTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("is_seed=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSeed))
	builder.WriteString(", ")
	if v := _m.ManagedSource; v != nil {
		builder.WriteString("managed_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SystemPromptTemplates is a parsable slice of SystemPromptTemplate.
type SystemPromptTemplates []*SystemPromptTemplate
