// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/systempromptruntime"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/systemprompttemplateversion"
)

// SystemPromptRuntimeUpdate is the builder for updating SystemPromptRuntime entities.
type SystemPromptRuntimeUpdate struct {
	config
	hooks    []Hook
	mutation *SystemPromptRuntimeMutation
}

// Where appends a list predicates to the SystemPromptRuntimeUpdate builder.
func (_u *SystemPromptRuntimeUpdate) Where(ps ...predicate.SystemPromptRuntime) *SystemPromptRuntimeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SystemPromptRuntimeUpdate) SetEnabled(v bool) *SystemPromptRuntimeUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdate) SetNillableEnabled(v *bool) *SystemPromptRuntimeUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetExposeServerPrompt sets the "expose_server_prompt" field.
func (_u *SystemPromptRuntimeUpdate) SetExposeServerPrompt(v bool) *SystemPromptRuntimeUpdate {
	_u.mutation.SetExposeServerPrompt(v)
	return _u
}

// SetNillableExposeServerPrompt sets the "expose_server_prompt" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdate) SetNillableExposeServerPrompt(v *bool) *SystemPromptRuntimeUpdate {
	if v != nil {
		_u.SetExposeServerPrompt(*v)
	}
	return _u
}

// SetCompactEnabled sets the "compact_enabled" field.
func (_u *SystemPromptRuntimeUpdate) SetCompactEnabled(v bool) *SystemPromptRuntimeUpdate {
	_u.mutation.SetCompactEnabled(v)
	return _u
}

// SetNillableCompactEnabled sets the "compact_enabled" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdate) SetNillableCompactEnabled(v *bool) *SystemPromptRuntimeUpdate {
	if v != nil {
		_u.SetCompactEnabled(*v)
	}
	return _u
}

// SetActiveTemplateID sets the "active_template_id" field.
func (_u *SystemPromptRuntimeUpdate) SetActiveTemplateID(v int64) *SystemPromptRuntimeUpdate {
	_u.mutation.SetActiveTemplateID(v)
	return _u
}

// SetNillableActiveTemplateID sets the "active_template_id" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdate) SetNillableActiveTemplateID(v *int64) *SystemPromptRuntimeUpdate {
	if v != nil {
		_u.SetActiveTemplateID(*v)
	}
	return _u
}

// ClearActiveTemplateID clears the value of the "active_template_id" field.
func (_u *SystemPromptRuntimeUpdate) ClearActiveTemplateID() *SystemPromptRuntimeUpdate {
	_u.mutation.ClearActiveTemplateID()
	return _u
}

// SetActiveVersionID sets the "active_version_id" field.
func (_u *SystemPromptRuntimeUpdate) SetActiveVersionID(v int64) *SystemPromptRuntimeUpdate {
	_u.mutation.SetActiveVersionID(v)
	return _u
}

// SetNillableActiveVersionID sets the "active_version_id" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdate) SetNillableActiveVersionID(v *int64) *SystemPromptRuntimeUpdate {
	if v != nil {
		_u.SetActiveVersionID(*v)
	}
	return _u
}

// ClearActiveVersionID clears the value of the "active_version_id" field.
func (_u *SystemPromptRuntimeUpdate) ClearActiveVersionID() *SystemPromptRuntimeUpdate {
	_u.mutation.ClearActiveVersionID()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *SystemPromptRuntimeUpdate) SetRevision(v int64) *SystemPromptRuntimeUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdate) SetNillableRevision(v *int64) *SystemPromptRuntimeUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *SystemPromptRuntimeUpdate) AddRevision(v int64) *SystemPromptRuntimeUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SystemPromptRuntimeUpdate) SetUpdatedBy(v int64) *SystemPromptRuntimeUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdate) SetNillableUpdatedBy(v *int64) *SystemPromptRuntimeUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SystemPromptRuntimeUpdate) AddUpdatedBy(v int64) *SystemPromptRuntimeUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SystemPromptRuntimeUpdate) ClearUpdatedBy() *SystemPromptRuntimeUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemPromptRuntimeUpdate) SetUpdatedAt(v time.Time) *SystemPromptRuntimeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetActiveTemplate sets the "active_template" edge to the SystemPromptTemplate entity.
func (_u *SystemPromptRuntimeUpdate) SetActiveTemplate(v *SystemPromptTemplate) *SystemPromptRuntimeUpdate {
	return _u.SetActiveTemplateID(v.ID)
}

// SetActiveVersion sets the "active_version" edge to the SystemPromptTemplateVersion entity.
func (_u *SystemPromptRuntimeUpdate) SetActiveVersion(v *SystemPromptTemplateVersion) *SystemPromptRuntimeUpdate {
	return _u.SetActiveVersionID(v.ID)
}

// Mutation returns the SystemPromptRuntimeMutation object of the builder.
func (_u *SystemPromptRuntimeUpdate) Mutation() *SystemPromptRuntimeMutation {
	return _u.mutation
}

// ClearActiveTemplate clears the "active_template" edge to the SystemPromptTemplate entity.
func (_u *SystemPromptRuntimeUpdate) ClearActiveTemplate() *SystemPromptRuntimeUpdate {
	_u.mutation.ClearActiveTemplate()
	return _u
}

// ClearActiveVersion clears the "active_version" edge to the SystemPromptTemplateVersion entity.
func (_u *SystemPromptRuntimeUpdate) ClearActiveVersion() *SystemPromptRuntimeUpdate {
	_u.mutation.ClearActiveVersion()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemPromptRuntimeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemPromptRuntimeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemPromptRuntimeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemPromptRuntimeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemPromptRuntimeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systempromptruntime.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SystemPromptRuntimeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(systempromptruntime.Table, systempromptruntime.Columns, sqlgraph.NewFieldSpec(systempromptruntime.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(systempromptruntime.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExposeServerPrompt(); ok {
		_spec.SetField(systempromptruntime.FieldExposeServerPrompt, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CompactEnabled(); ok {
		_spec.SetField(systempromptruntime.FieldCompactEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(systempromptruntime.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(systempromptruntime.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(systempromptruntime.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(systempromptruntime.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(systempromptruntime.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systempromptruntime.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActiveTemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systempromptruntime.ActiveTemplateTable,
			Columns: []string{systempromptruntime.ActiveTemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActiveTemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systempromptruntime.ActiveTemplateTable,
			Columns: []string{systempromptruntime.ActiveTemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActiveVersionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systempromptruntime.ActiveVersionTable,
			Columns: []string{systempromptruntime.ActiveVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplateversion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActiveVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systempromptruntime.ActiveVersionTable,
			Columns: []string{systempromptruntime.ActiveVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplateversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systempromptruntime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemPromptRuntimeUpdateOne is the builder for updating a single SystemPromptRuntime entity.
type SystemPromptRuntimeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemPromptRuntimeMutation
}

// SetEnabled sets the "enabled" field.
func (_u *SystemPromptRuntimeUpdateOne) SetEnabled(v bool) *SystemPromptRuntimeUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdateOne) SetNillableEnabled(v *bool) *SystemPromptRuntimeUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetExposeServerPrompt sets the "expose_server_prompt" field.
func (_u *SystemPromptRuntimeUpdateOne) SetExposeServerPrompt(v bool) *SystemPromptRuntimeUpdateOne {
	_u.mutation.SetExposeServerPrompt(v)
	return _u
}

// SetNillableExposeServerPrompt sets the "expose_server_prompt" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdateOne) SetNillableExposeServerPrompt(v *bool) *SystemPromptRuntimeUpdateOne {
	if v != nil {
		_u.SetExposeServerPrompt(*v)
	}
	return _u
}

// SetCompactEnabled sets the "compact_enabled" field.
func (_u *SystemPromptRuntimeUpdateOne) SetCompactEnabled(v bool) *SystemPromptRuntimeUpdateOne {
	_u.mutation.SetCompactEnabled(v)
	return _u
}

// SetNillableCompactEnabled sets the "compact_enabled" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdateOne) SetNillableCompactEnabled(v *bool) *SystemPromptRuntimeUpdateOne {
	if v != nil {
		_u.SetCompactEnabled(*v)
	}
	return _u
}

// SetActiveTemplateID sets the "active_template_id" field.
func (_u *SystemPromptRuntimeUpdateOne) SetActiveTemplateID(v int64) *SystemPromptRuntimeUpdateOne {
	_u.mutation.SetActiveTemplateID(v)
	return _u
}

// SetNillableActiveTemplateID sets the "active_template_id" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdateOne) SetNillableActiveTemplateID(v *int64) *SystemPromptRuntimeUpdateOne {
	if v != nil {
		_u.SetActiveTemplateID(*v)
	}
	return _u
}

// ClearActiveTemplateID clears the value of the "active_template_id" field.
func (_u *SystemPromptRuntimeUpdateOne) ClearActiveTemplateID() *SystemPromptRuntimeUpdateOne {
	_u.mutation.ClearActiveTemplateID()
	return _u
}

// SetActiveVersionID sets the "active_version_id" field.
func (_u *SystemPromptRuntimeUpdateOne) SetActiveVersionID(v int64) *SystemPromptRuntimeUpdateOne {
	_u.mutation.SetActiveVersionID(v)
	return _u
}

// SetNillableActiveVersionID sets the "active_version_id" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdateOne) SetNillableActiveVersionID(v *int64) *SystemPromptRuntimeUpdateOne {
	if v != nil {
		_u.SetActiveVersionID(*v)
	}
	return _u
}

// ClearActiveVersionID clears the value of the "active_version_id" field.
func (_u *SystemPromptRuntimeUpdateOne) ClearActiveVersionID() *SystemPromptRuntimeUpdateOne {
	_u.mutation.ClearActiveVersionID()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *SystemPromptRuntimeUpdateOne) SetRevision(v int64) *SystemPromptRuntimeUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdateOne) SetNillableRevision(v *int64) *SystemPromptRuntimeUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *SystemPromptRuntimeUpdateOne) AddRevision(v int64) *SystemPromptRuntimeUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SystemPromptRuntimeUpdateOne) SetUpdatedBy(v int64) *SystemPromptRuntimeUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SystemPromptRuntimeUpdateOne) SetNillableUpdatedBy(v *int64) *SystemPromptRuntimeUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SystemPromptRuntimeUpdateOne) AddUpdatedBy(v int64) *SystemPromptRuntimeUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SystemPromptRuntimeUpdateOne) ClearUpdatedBy() *SystemPromptRuntimeUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemPromptRuntimeUpdateOne) SetUpdatedAt(v time.Time) *SystemPromptRuntimeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetActiveTemplate sets the "active_template" edge to the SystemPromptTemplate entity.
func (_u *SystemPromptRuntimeUpdateOne) SetActiveTemplate(v *SystemPromptTemplate) *SystemPromptRuntimeUpdateOne {
	return _u.SetActiveTemplateID(v.ID)
}

// SetActiveVersion sets the "active_version" edge to the SystemPromptTemplateVersion entity.
func (_u *SystemPromptRuntimeUpdateOne) SetActiveVersion(v *SystemPromptTemplateVersion) *SystemPromptRuntimeUpdateOne {
	return _u.SetActiveVersionID(v.ID)
}

// Mutation returns the SystemPromptRuntimeMutation object of the builder.
func (_u *SystemPromptRuntimeUpdateOne) Mutation() *SystemPromptRuntimeMutation {
	return _u.mutation
}

// ClearActiveTemplate clears the "active_template" edge to the SystemPromptTemplate entity.
func (_u *SystemPromptRuntimeUpdateOne) ClearActiveTemplate() *SystemPromptRuntimeUpdateOne {
	_u.mutation.ClearActiveTemplate()
	return _u
}

// ClearActiveVersion clears the "active_version" edge to the SystemPromptTemplateVersion entity.
func (_u *SystemPromptRuntimeUpdateOne) ClearActiveVersion() *SystemPromptRuntimeUpdateOne {
	_u.mutation.ClearActiveVersion()
	return _u
}

// Where appends a list predicates to the SystemPromptRuntimeUpdate builder.
func (_u *SystemPromptRuntimeUpdateOne) Where(ps ...predicate.SystemPromptRuntime) *SystemPromptRuntimeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemPromptRuntimeUpdateOne) Select(field string, fields ...string) *SystemPromptRuntimeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemPromptRuntime entity.
func (_u *SystemPromptRuntimeUpdateOne) Save(ctx context.Context) (*SystemPromptRuntime, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemPromptRuntimeUpdateOne) SaveX(ctx context.Context) *SystemPromptRuntime {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemPromptRuntimeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemPromptRuntimeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemPromptRuntimeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systempromptruntime.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SystemPromptRuntimeUpdateOne) sqlSave(ctx context.Context) (_node *SystemPromptRuntime, err error) {
	_spec := sqlgraph.NewUpdateSpec(systempromptruntime.Table, systempromptruntime.Columns, sqlgraph.NewFieldSpec(systempromptruntime.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemPromptRuntime.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systempromptruntime.FieldID)
		for _, f := range fields {
			if !systempromptruntime.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systempromptruntime.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(systempromptruntime.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExposeServerPrompt(); ok {
		_spec.SetField(systempromptruntime.FieldExposeServerPrompt, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CompactEnabled(); ok {
		_spec.SetField(systempromptruntime.FieldCompactEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(systempromptruntime.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(systempromptruntime.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(systempromptruntime.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(systempromptruntime.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(systempromptruntime.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systempromptruntime.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActiveTemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systempromptruntime.ActiveTemplateTable,
			Columns: []string{systempromptruntime.ActiveTemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActiveTemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systempromptruntime.ActiveTemplateTable,
			Columns: []string{systempromptruntime.ActiveTemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActiveVersionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systempromptruntime.ActiveVersionTable,
			Columns: []string{systempromptruntime.ActiveVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplateversion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActiveVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   systempromptruntime.ActiveVersionTable,
			Columns: []string{systempromptruntime.ActiveVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemprompttemplateversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SystemPromptRuntime{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systempromptruntime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
