// Code generated by ent, DO NOT EDIT.

package systemprompttemplateversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the systemprompttemplateversion type in the database.
	Label = "system_prompt_template_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTemplateID holds the string denoting the template_id field in the database.
	FieldTemplateID = "template_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldSha256 holds the string denoting the sha256 field in the database.
	FieldSha256 = "sha256"
	// FieldByteLength holds the string denoting the byte_length field in the database.
	FieldByteLength = "byte_length"
	// FieldCompositionMode holds the string denoting the composition_mode field in the database.
	FieldCompositionMode = "composition_mode"
	// FieldBundleID holds the string denoting the bundle_id field in the database.
	FieldBundleID = "bundle_id"
	// FieldBundleManifestSha256 holds the string denoting the bundle_manifest_sha256 field in the database.
	FieldBundleManifestSha256 = "bundle_manifest_sha256"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldPublishedBy holds the string denoting the published_by field in the database.
	FieldPublishedBy = "published_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTemplate holds the string denoting the template edge name in mutations.
	EdgeTemplate = "template"
	// Table holds the table name of the systemprompttemplateversion in the database.
	Table = "system_prompt_template_versions"
	// TemplateTable is the table that holds the template relation/edge.
	TemplateTable = "system_prompt_template_versions"
	// TemplateInverseTable is the table name for the SystemPromptTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "systemprompttemplate" package.
	TemplateInverseTable = "system_prompt_templates"
	// TemplateColumn is the table column denoting the template relation/edge.
	TemplateColumn = "template_id"
)

// Columns holds all SQL columns for systemprompttemplateversion fields.
var Columns = []string{
	FieldID,
	FieldTemplateID,
	FieldVersion,
	FieldBody,
	FieldSha256,
	FieldByteLength,
	FieldCompositionMode,
	FieldBundleID,
	FieldBundleManifestSha256,
	FieldNote,
	FieldCreatedBy,
	FieldPublishedAt,
	FieldPublishedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BodyValidator is a validator for the "body" field. It is called by the builders before save.
	BodyValidator func(string) error
	// Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	Sha256Validator func(string) error
	// ByteLengthValidator is a validator for the "byte_length" field. It is called by the builders before save.
	ByteLengthValidator func(int) error
	// DefaultCompositionMode holds the default value on creation for the "composition_mode" field.
	DefaultCompositionMode string
	// CompositionModeValidator is a validator for the "composition_mode" field. It is called by the builders before save.
	CompositionModeValidator func(string) error
	// BundleIDValidator is a validator for the "bundle_id" field. It is called by the builders before save.
	BundleIDValidator func(string) error
	// BundleManifestSha256Validator is a validator for the "bundle_manifest_sha256" field. It is called by the builders before save.
	BundleManifestSha256Validator func(string) error
	// DefaultNote holds the default value on creation for the "note" field.
	DefaultNote string
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SystemPromptTemplateVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTemplateID orders the results by the template_id field.
func ByTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// BySha256 orders the results by the sha256 field.
func BySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSha256, opts...).ToFunc()
}

// ByByteLength orders the results by the byte_length field.
func ByByteLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldByteLength, opts...).ToFunc()
}

// ByCompositionMode orders the results by the composition_mode field.
func ByCompositionMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompositionMode, opts...).ToFunc()
}

// ByBundleID orders the results by the bundle_id field.
func ByBundleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBundleID, opts...).ToFunc()
}

// ByBundleManifestSha256 orders the results by the bundle_manifest_sha256 field.
func ByBundleManifestSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBundleManifestSha256, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByPublishedBy orders the results by the published_by field.
func ByPublishedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTemplateField orders the results by template field.
func ByTemplateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTemplateStep(), sql.OrderByField(field, opts...))
	}
}
func newTemplateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TemplateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
	)
}
