// Code generated by ent, DO NOT EDIT.

package systemprompttemplateversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldID, id))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldTemplateID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldVersion, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldBody, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSha256, v))
}

// ByteLength applies equality check predicate on the "byte_length" field. It's identical to ByteLengthEQ.
func ByteLength(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldByteLength, v))
}

// CompositionMode applies equality check predicate on the "composition_mode" field. It's identical to CompositionModeEQ.
func CompositionMode(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCompositionMode, v))
}

// BundleID applies equality check predicate on the "bundle_id" field. It's identical to BundleIDEQ.
func BundleID(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldBundleID, v))
}

// BundleManifestSha256 applies equality check predicate on the "bundle_manifest_sha256" field. It's identical to BundleManifestSha256EQ.
func BundleManifestSha256(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldBundleManifestSha256, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldNote, v))
}

// SourceRepository applies equality check predicate on the "source_repository" field. It's identical to SourceRepositoryEQ.
func SourceRepository(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceRepository, v))
}

// SourceCommit applies equality check predicate on the "source_commit" field. It's identical to SourceCommitEQ.
func SourceCommit(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceCommit, v))
}

// SourceVersion applies equality check predicate on the "source_version" field. It's identical to SourceVersionEQ.
func SourceVersion(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceVersion, v))
}

// SourceArtifact applies equality check predicate on the "source_artifact" field. It's identical to SourceArtifactEQ.
func SourceArtifact(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceArtifact, v))
}

// SourceArtifactSha256 applies equality check predicate on the "source_artifact_sha256" field. It's identical to SourceArtifactSha256EQ.
func SourceArtifactSha256(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceArtifactSha256, v))
}

// SourceLicenseSha256 applies equality check predicate on the "source_license_sha256" field. It's identical to SourceLicenseSha256EQ.
func SourceLicenseSha256(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceLicenseSha256, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedBy applies equality check predicate on the "published_by" field. It's identical to PublishedByEQ.
func PublishedBy(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldPublishedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldTemplateID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldVersion, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldBody, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldSha256, v))
}

// ByteLengthEQ applies the EQ predicate on the "byte_length" field.
func ByteLengthEQ(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldByteLength, v))
}

// ByteLengthNEQ applies the NEQ predicate on the "byte_length" field.
func ByteLengthNEQ(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldByteLength, v))
}

// ByteLengthIn applies the In predicate on the "byte_length" field.
func ByteLengthIn(vs ...int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldByteLength, vs...))
}

// ByteLengthNotIn applies the NotIn predicate on the "byte_length" field.
func ByteLengthNotIn(vs ...int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldByteLength, vs...))
}

// ByteLengthGT applies the GT predicate on the "byte_length" field.
func ByteLengthGT(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldByteLength, v))
}

// ByteLengthGTE applies the GTE predicate on the "byte_length" field.
func ByteLengthGTE(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldByteLength, v))
}

// ByteLengthLT applies the LT predicate on the "byte_length" field.
func ByteLengthLT(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldByteLength, v))
}

// ByteLengthLTE applies the LTE predicate on the "byte_length" field.
func ByteLengthLTE(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldByteLength, v))
}

// CompositionModeEQ applies the EQ predicate on the "composition_mode" field.
func CompositionModeEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCompositionMode, v))
}

// CompositionModeNEQ applies the NEQ predicate on the "composition_mode" field.
func CompositionModeNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldCompositionMode, v))
}

// CompositionModeIn applies the In predicate on the "composition_mode" field.
func CompositionModeIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldCompositionMode, vs...))
}

// CompositionModeNotIn applies the NotIn predicate on the "composition_mode" field.
func CompositionModeNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldCompositionMode, vs...))
}

// CompositionModeGT applies the GT predicate on the "composition_mode" field.
func CompositionModeGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldCompositionMode, v))
}

// CompositionModeGTE applies the GTE predicate on the "composition_mode" field.
func CompositionModeGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldCompositionMode, v))
}

// CompositionModeLT applies the LT predicate on the "composition_mode" field.
func CompositionModeLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldCompositionMode, v))
}

// CompositionModeLTE applies the LTE predicate on the "composition_mode" field.
func CompositionModeLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldCompositionMode, v))
}

// CompositionModeContains applies the Contains predicate on the "composition_mode" field.
func CompositionModeContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldCompositionMode, v))
}

// CompositionModeHasPrefix applies the HasPrefix predicate on the "composition_mode" field.
func CompositionModeHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldCompositionMode, v))
}

// CompositionModeHasSuffix applies the HasSuffix predicate on the "composition_mode" field.
func CompositionModeHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldCompositionMode, v))
}

// CompositionModeEqualFold applies the EqualFold predicate on the "composition_mode" field.
func CompositionModeEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldCompositionMode, v))
}

// CompositionModeContainsFold applies the ContainsFold predicate on the "composition_mode" field.
func CompositionModeContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldCompositionMode, v))
}

// BundleIDEQ applies the EQ predicate on the "bundle_id" field.
func BundleIDEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldBundleID, v))
}

// BundleIDNEQ applies the NEQ predicate on the "bundle_id" field.
func BundleIDNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldBundleID, v))
}

// BundleIDIn applies the In predicate on the "bundle_id" field.
func BundleIDIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldBundleID, vs...))
}

// BundleIDNotIn applies the NotIn predicate on the "bundle_id" field.
func BundleIDNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldBundleID, vs...))
}

// BundleIDGT applies the GT predicate on the "bundle_id" field.
func BundleIDGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldBundleID, v))
}

// BundleIDGTE applies the GTE predicate on the "bundle_id" field.
func BundleIDGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldBundleID, v))
}

// BundleIDLT applies the LT predicate on the "bundle_id" field.
func BundleIDLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldBundleID, v))
}

// BundleIDLTE applies the LTE predicate on the "bundle_id" field.
func BundleIDLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldBundleID, v))
}

// BundleIDContains applies the Contains predicate on the "bundle_id" field.
func BundleIDContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldBundleID, v))
}

// BundleIDHasPrefix applies the HasPrefix predicate on the "bundle_id" field.
func BundleIDHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldBundleID, v))
}

// BundleIDHasSuffix applies the HasSuffix predicate on the "bundle_id" field.
func BundleIDHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldBundleID, v))
}

// BundleIDIsNil applies the IsNil predicate on the "bundle_id" field.
func BundleIDIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldBundleID))
}

// BundleIDNotNil applies the NotNil predicate on the "bundle_id" field.
func BundleIDNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldBundleID))
}

// BundleIDEqualFold applies the EqualFold predicate on the "bundle_id" field.
func BundleIDEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldBundleID, v))
}

// BundleIDContainsFold applies the ContainsFold predicate on the "bundle_id" field.
func BundleIDContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldBundleID, v))
}

// BundleManifestSha256EQ applies the EQ predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256EQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldBundleManifestSha256, v))
}

// BundleManifestSha256NEQ applies the NEQ predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256NEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldBundleManifestSha256, v))
}

// BundleManifestSha256In applies the In predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256In(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldBundleManifestSha256, vs...))
}

// BundleManifestSha256NotIn applies the NotIn predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256NotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldBundleManifestSha256, vs...))
}

// BundleManifestSha256GT applies the GT predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256GT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldBundleManifestSha256, v))
}

// BundleManifestSha256GTE applies the GTE predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256GTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldBundleManifestSha256, v))
}

// BundleManifestSha256LT applies the LT predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256LT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldBundleManifestSha256, v))
}

// BundleManifestSha256LTE applies the LTE predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256LTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldBundleManifestSha256, v))
}

// BundleManifestSha256Contains applies the Contains predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256Contains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldBundleManifestSha256, v))
}

// BundleManifestSha256HasPrefix applies the HasPrefix predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256HasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldBundleManifestSha256, v))
}

// BundleManifestSha256HasSuffix applies the HasSuffix predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256HasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldBundleManifestSha256, v))
}

// BundleManifestSha256IsNil applies the IsNil predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256IsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldBundleManifestSha256))
}

// BundleManifestSha256NotNil applies the NotNil predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256NotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldBundleManifestSha256))
}

// BundleManifestSha256EqualFold applies the EqualFold predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256EqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldBundleManifestSha256, v))
}

// BundleManifestSha256ContainsFold applies the ContainsFold predicate on the "bundle_manifest_sha256" field.
func BundleManifestSha256ContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldBundleManifestSha256, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldNote, v))
}

// SourceRepositoryEQ applies the EQ predicate on the "source_repository" field.
func SourceRepositoryEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceRepository, v))
}

// SourceRepositoryNEQ applies the NEQ predicate on the "source_repository" field.
func SourceRepositoryNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldSourceRepository, v))
}

// SourceRepositoryIn applies the In predicate on the "source_repository" field.
func SourceRepositoryIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldSourceRepository, vs...))
}

// SourceRepositoryNotIn applies the NotIn predicate on the "source_repository" field.
func SourceRepositoryNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldSourceRepository, vs...))
}

// SourceRepositoryGT applies the GT predicate on the "source_repository" field.
func SourceRepositoryGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldSourceRepository, v))
}

// SourceRepositoryGTE applies the GTE predicate on the "source_repository" field.
func SourceRepositoryGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldSourceRepository, v))
}

// SourceRepositoryLT applies the LT predicate on the "source_repository" field.
func SourceRepositoryLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldSourceRepository, v))
}

// SourceRepositoryLTE applies the LTE predicate on the "source_repository" field.
func SourceRepositoryLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldSourceRepository, v))
}

// SourceRepositoryContains applies the Contains predicate on the "source_repository" field.
func SourceRepositoryContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldSourceRepository, v))
}

// SourceRepositoryHasPrefix applies the HasPrefix predicate on the "source_repository" field.
func SourceRepositoryHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldSourceRepository, v))
}

// SourceRepositoryHasSuffix applies the HasSuffix predicate on the "source_repository" field.
func SourceRepositoryHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldSourceRepository, v))
}

// SourceRepositoryIsNil applies the IsNil predicate on the "source_repository" field.
func SourceRepositoryIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldSourceRepository))
}

// SourceRepositoryNotNil applies the NotNil predicate on the "source_repository" field.
func SourceRepositoryNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldSourceRepository))
}

// SourceRepositoryEqualFold applies the EqualFold predicate on the "source_repository" field.
func SourceRepositoryEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldSourceRepository, v))
}

// SourceRepositoryContainsFold applies the ContainsFold predicate on the "source_repository" field.
func SourceRepositoryContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldSourceRepository, v))
}

// SourceCommitEQ applies the EQ predicate on the "source_commit" field.
func SourceCommitEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceCommit, v))
}

// SourceCommitNEQ applies the NEQ predicate on the "source_commit" field.
func SourceCommitNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldSourceCommit, v))
}

// SourceCommitIn applies the In predicate on the "source_commit" field.
func SourceCommitIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldSourceCommit, vs...))
}

// SourceCommitNotIn applies the NotIn predicate on the "source_commit" field.
func SourceCommitNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldSourceCommit, vs...))
}

// SourceCommitGT applies the GT predicate on the "source_commit" field.
func SourceCommitGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldSourceCommit, v))
}

// SourceCommitGTE applies the GTE predicate on the "source_commit" field.
func SourceCommitGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldSourceCommit, v))
}

// SourceCommitLT applies the LT predicate on the "source_commit" field.
func SourceCommitLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldSourceCommit, v))
}

// SourceCommitLTE applies the LTE predicate on the "source_commit" field.
func SourceCommitLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldSourceCommit, v))
}

// SourceCommitContains applies the Contains predicate on the "source_commit" field.
func SourceCommitContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldSourceCommit, v))
}

// SourceCommitHasPrefix applies the HasPrefix predicate on the "source_commit" field.
func SourceCommitHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldSourceCommit, v))
}

// SourceCommitHasSuffix applies the HasSuffix predicate on the "source_commit" field.
func SourceCommitHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldSourceCommit, v))
}

// SourceCommitIsNil applies the IsNil predicate on the "source_commit" field.
func SourceCommitIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldSourceCommit))
}

// SourceCommitNotNil applies the NotNil predicate on the "source_commit" field.
func SourceCommitNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldSourceCommit))
}

// SourceCommitEqualFold applies the EqualFold predicate on the "source_commit" field.
func SourceCommitEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldSourceCommit, v))
}

// SourceCommitContainsFold applies the ContainsFold predicate on the "source_commit" field.
func SourceCommitContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldSourceCommit, v))
}

// SourceVersionEQ applies the EQ predicate on the "source_version" field.
func SourceVersionEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceVersion, v))
}

// SourceVersionNEQ applies the NEQ predicate on the "source_version" field.
func SourceVersionNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldSourceVersion, v))
}

// SourceVersionIn applies the In predicate on the "source_version" field.
func SourceVersionIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldSourceVersion, vs...))
}

// SourceVersionNotIn applies the NotIn predicate on the "source_version" field.
func SourceVersionNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldSourceVersion, vs...))
}

// SourceVersionGT applies the GT predicate on the "source_version" field.
func SourceVersionGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldSourceVersion, v))
}

// SourceVersionGTE applies the GTE predicate on the "source_version" field.
func SourceVersionGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldSourceVersion, v))
}

// SourceVersionLT applies the LT predicate on the "source_version" field.
func SourceVersionLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldSourceVersion, v))
}

// SourceVersionLTE applies the LTE predicate on the "source_version" field.
func SourceVersionLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldSourceVersion, v))
}

// SourceVersionContains applies the Contains predicate on the "source_version" field.
func SourceVersionContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldSourceVersion, v))
}

// SourceVersionHasPrefix applies the HasPrefix predicate on the "source_version" field.
func SourceVersionHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldSourceVersion, v))
}

// SourceVersionHasSuffix applies the HasSuffix predicate on the "source_version" field.
func SourceVersionHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldSourceVersion, v))
}

// SourceVersionIsNil applies the IsNil predicate on the "source_version" field.
func SourceVersionIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldSourceVersion))
}

// SourceVersionNotNil applies the NotNil predicate on the "source_version" field.
func SourceVersionNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldSourceVersion))
}

// SourceVersionEqualFold applies the EqualFold predicate on the "source_version" field.
func SourceVersionEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldSourceVersion, v))
}

// SourceVersionContainsFold applies the ContainsFold predicate on the "source_version" field.
func SourceVersionContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldSourceVersion, v))
}

// SourceArtifactEQ applies the EQ predicate on the "source_artifact" field.
func SourceArtifactEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceArtifact, v))
}

// SourceArtifactNEQ applies the NEQ predicate on the "source_artifact" field.
func SourceArtifactNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldSourceArtifact, v))
}

// SourceArtifactIn applies the In predicate on the "source_artifact" field.
func SourceArtifactIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldSourceArtifact, vs...))
}

// SourceArtifactNotIn applies the NotIn predicate on the "source_artifact" field.
func SourceArtifactNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldSourceArtifact, vs...))
}

// SourceArtifactGT applies the GT predicate on the "source_artifact" field.
func SourceArtifactGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldSourceArtifact, v))
}

// SourceArtifactGTE applies the GTE predicate on the "source_artifact" field.
func SourceArtifactGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldSourceArtifact, v))
}

// SourceArtifactLT applies the LT predicate on the "source_artifact" field.
func SourceArtifactLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldSourceArtifact, v))
}

// SourceArtifactLTE applies the LTE predicate on the "source_artifact" field.
func SourceArtifactLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldSourceArtifact, v))
}

// SourceArtifactContains applies the Contains predicate on the "source_artifact" field.
func SourceArtifactContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldSourceArtifact, v))
}

// SourceArtifactHasPrefix applies the HasPrefix predicate on the "source_artifact" field.
func SourceArtifactHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldSourceArtifact, v))
}

// SourceArtifactHasSuffix applies the HasSuffix predicate on the "source_artifact" field.
func SourceArtifactHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldSourceArtifact, v))
}

// SourceArtifactIsNil applies the IsNil predicate on the "source_artifact" field.
func SourceArtifactIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldSourceArtifact))
}

// SourceArtifactNotNil applies the NotNil predicate on the "source_artifact" field.
func SourceArtifactNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldSourceArtifact))
}

// SourceArtifactEqualFold applies the EqualFold predicate on the "source_artifact" field.
func SourceArtifactEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldSourceArtifact, v))
}

// SourceArtifactContainsFold applies the ContainsFold predicate on the "source_artifact" field.
func SourceArtifactContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldSourceArtifact, v))
}

// SourceArtifactSha256EQ applies the EQ predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256EQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256NEQ applies the NEQ predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256NEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256In applies the In predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256In(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldSourceArtifactSha256, vs...))
}

// SourceArtifactSha256NotIn applies the NotIn predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256NotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldSourceArtifactSha256, vs...))
}

// SourceArtifactSha256GT applies the GT predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256GT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256GTE applies the GTE predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256GTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256LT applies the LT predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256LT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256LTE applies the LTE predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256LTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256Contains applies the Contains predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256Contains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256HasPrefix applies the HasPrefix predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256HasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256HasSuffix applies the HasSuffix predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256HasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256IsNil applies the IsNil predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256IsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldSourceArtifactSha256))
}

// SourceArtifactSha256NotNil applies the NotNil predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256NotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldSourceArtifactSha256))
}

// SourceArtifactSha256EqualFold applies the EqualFold predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256EqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldSourceArtifactSha256, v))
}

// SourceArtifactSha256ContainsFold applies the ContainsFold predicate on the "source_artifact_sha256" field.
func SourceArtifactSha256ContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldSourceArtifactSha256, v))
}

// SourceLicenseSha256EQ applies the EQ predicate on the "source_license_sha256" field.
func SourceLicenseSha256EQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256NEQ applies the NEQ predicate on the "source_license_sha256" field.
func SourceLicenseSha256NEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256In applies the In predicate on the "source_license_sha256" field.
func SourceLicenseSha256In(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldSourceLicenseSha256, vs...))
}

// SourceLicenseSha256NotIn applies the NotIn predicate on the "source_license_sha256" field.
func SourceLicenseSha256NotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldSourceLicenseSha256, vs...))
}

// SourceLicenseSha256GT applies the GT predicate on the "source_license_sha256" field.
func SourceLicenseSha256GT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256GTE applies the GTE predicate on the "source_license_sha256" field.
func SourceLicenseSha256GTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256LT applies the LT predicate on the "source_license_sha256" field.
func SourceLicenseSha256LT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256LTE applies the LTE predicate on the "source_license_sha256" field.
func SourceLicenseSha256LTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256Contains applies the Contains predicate on the "source_license_sha256" field.
func SourceLicenseSha256Contains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256HasPrefix applies the HasPrefix predicate on the "source_license_sha256" field.
func SourceLicenseSha256HasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256HasSuffix applies the HasSuffix predicate on the "source_license_sha256" field.
func SourceLicenseSha256HasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256IsNil applies the IsNil predicate on the "source_license_sha256" field.
func SourceLicenseSha256IsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldSourceLicenseSha256))
}

// SourceLicenseSha256NotNil applies the NotNil predicate on the "source_license_sha256" field.
func SourceLicenseSha256NotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldSourceLicenseSha256))
}

// SourceLicenseSha256EqualFold applies the EqualFold predicate on the "source_license_sha256" field.
func SourceLicenseSha256EqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldSourceLicenseSha256, v))
}

// SourceLicenseSha256ContainsFold applies the ContainsFold predicate on the "source_license_sha256" field.
func SourceLicenseSha256ContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldSourceLicenseSha256, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldCreatedBy))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldPublishedAt))
}

// PublishedByEQ applies the EQ predicate on the "published_by" field.
func PublishedByEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldPublishedBy, v))
}

// PublishedByNEQ applies the NEQ predicate on the "published_by" field.
func PublishedByNEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldPublishedBy, v))
}

// PublishedByIn applies the In predicate on the "published_by" field.
func PublishedByIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldPublishedBy, vs...))
}

// PublishedByNotIn applies the NotIn predicate on the "published_by" field.
func PublishedByNotIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldPublishedBy, vs...))
}

// PublishedByGT applies the GT predicate on the "published_by" field.
func PublishedByGT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldPublishedBy, v))
}

// PublishedByGTE applies the GTE predicate on the "published_by" field.
func PublishedByGTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldPublishedBy, v))
}

// PublishedByLT applies the LT predicate on the "published_by" field.
func PublishedByLT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldPublishedBy, v))
}

// PublishedByLTE applies the LTE predicate on the "published_by" field.
func PublishedByLTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldPublishedBy, v))
}

// PublishedByIsNil applies the IsNil predicate on the "published_by" field.
func PublishedByIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldPublishedBy))
}

// PublishedByNotNil applies the NotNil predicate on the "published_by" field.
func PublishedByNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldPublishedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTemplate applies the HasEdge predicate on the "template" edge.
func HasTemplate() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTemplateWith applies the HasEdge predicate on the "template" edge with a given conditions (other predicates).
func HasTemplateWith(preds ...predicate.SystemPromptTemplate) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(func(s *sql.Selector) {
		step := newTemplateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SystemPromptTemplateVersion) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SystemPromptTemplateVersion) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SystemPromptTemplateVersion) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.NotPredicates(p))
}
