// Code generated by ent, DO NOT EDIT.

package systemprompttemplateversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldID, id))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldTemplateID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldVersion, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldBody, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSha256, v))
}

// ByteLength applies equality check predicate on the "byte_length" field. It's identical to ByteLengthEQ.
func ByteLength(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldByteLength, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldNote, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedBy applies equality check predicate on the "published_by" field. It's identical to PublishedByEQ.
func PublishedBy(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldPublishedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldTemplateID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldVersion, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldBody, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldSha256, v))
}

// ByteLengthEQ applies the EQ predicate on the "byte_length" field.
func ByteLengthEQ(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldByteLength, v))
}

// ByteLengthNEQ applies the NEQ predicate on the "byte_length" field.
func ByteLengthNEQ(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldByteLength, v))
}

// ByteLengthIn applies the In predicate on the "byte_length" field.
func ByteLengthIn(vs ...int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldByteLength, vs...))
}

// ByteLengthNotIn applies the NotIn predicate on the "byte_length" field.
func ByteLengthNotIn(vs ...int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldByteLength, vs...))
}

// ByteLengthGT applies the GT predicate on the "byte_length" field.
func ByteLengthGT(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldByteLength, v))
}

// ByteLengthGTE applies the GTE predicate on the "byte_length" field.
func ByteLengthGTE(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldByteLength, v))
}

// ByteLengthLT applies the LT predicate on the "byte_length" field.
func ByteLengthLT(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldByteLength, v))
}

// ByteLengthLTE applies the LTE predicate on the "byte_length" field.
func ByteLengthLTE(v int) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldByteLength, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldContainsFold(FieldNote, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldCreatedBy))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldPublishedAt))
}

// PublishedByEQ applies the EQ predicate on the "published_by" field.
func PublishedByEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldPublishedBy, v))
}

// PublishedByNEQ applies the NEQ predicate on the "published_by" field.
func PublishedByNEQ(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldPublishedBy, v))
}

// PublishedByIn applies the In predicate on the "published_by" field.
func PublishedByIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldPublishedBy, vs...))
}

// PublishedByNotIn applies the NotIn predicate on the "published_by" field.
func PublishedByNotIn(vs ...int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldPublishedBy, vs...))
}

// PublishedByGT applies the GT predicate on the "published_by" field.
func PublishedByGT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldPublishedBy, v))
}

// PublishedByGTE applies the GTE predicate on the "published_by" field.
func PublishedByGTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldPublishedBy, v))
}

// PublishedByLT applies the LT predicate on the "published_by" field.
func PublishedByLT(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldPublishedBy, v))
}

// PublishedByLTE applies the LTE predicate on the "published_by" field.
func PublishedByLTE(v int64) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldPublishedBy, v))
}

// PublishedByIsNil applies the IsNil predicate on the "published_by" field.
func PublishedByIsNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIsNull(FieldPublishedBy))
}

// PublishedByNotNil applies the NotNil predicate on the "published_by" field.
func PublishedByNotNil() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotNull(FieldPublishedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTemplate applies the HasEdge predicate on the "template" edge.
func HasTemplate() predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTemplateWith applies the HasEdge predicate on the "template" edge with a given conditions (other predicates).
func HasTemplateWith(preds ...predicate.SystemPromptTemplate) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(func(s *sql.Selector) {
		step := newTemplateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SystemPromptTemplateVersion) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SystemPromptTemplateVersion) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SystemPromptTemplateVersion) predicate.SystemPromptTemplateVersion {
	return predicate.SystemPromptTemplateVersion(sql.NotPredicates(p))
}
