package service

var cindyCapabilityCatalog = []CindyCapability{
	newCindyV4ChatCapability("claude-opus-4-8", "anthropic/claude-opus-4-8", "Claude Opus 4.8", "Most capable, supports xhigh effort", 1000000, 128000, []string{"text", "image", "file"}, []string{"low", "medium", "high", "xhigh", "max"}, "high", 0, CindyTextPricing{InputCostPerToken: 5e-6, OutputCostPerToken: 25e-6, CacheReadInputTokenCost: 0.5e-6, CacheCreationInputTokenCost: 6.25e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("claude-opus-5", "anthropic/claude-opus-5", "Claude Opus 5", "Latest Opus for ambitious work", 1000000, 128000, []string{"text", "image", "file"}, []string{"low", "medium", "high", "xhigh", "max"}, "high", 0, CindyTextPricing{InputCostPerToken: 5e-6, OutputCostPerToken: 25e-6, CacheReadInputTokenCost: 0.5e-6, CacheCreationInputTokenCost: 6.25e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("claude-sonnet-5", "anthropic/claude-sonnet-5", "Claude Sonnet 5", "Latest Sonnet — fast and highly capable", 1000000, 128000, []string{"text", "image", "file"}, []string{"low", "medium", "high", "xhigh", "max"}, "high", 0, CindyTextPricing{InputCostPerToken: 2e-6, OutputCostPerToken: 10e-6, CacheReadInputTokenCost: 0.2e-6, CacheCreationInputTokenCost: 2.5e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("seed-2.1-pro", "bytedance-seed/seed-2.1-pro", "Doubao Seed 2.1 Pro", "", 256000, 256000, []string{"text", "image", "video"}, []string{"minimal", "low", "medium", "high"}, "minimal", 0, CindyTextPricing{InputCostPerToken: 0.88e-6, OutputCostPerToken: 4.4e-6, CacheReadInputTokenCost: 0.18e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("deepseek-v4-flash", "deepseek/deepseek-v4-flash", "DeepSeek V4 Flash", "DeepSeek V4 Flash efficiency-optimized MoE; supports low/high/max effort", 1000000, 384000, []string{"text"}, []string{"medium", "high", "max"}, "high", 0, CindyTextPricing{InputCostPerToken: 0.44e-6, OutputCostPerToken: 1.32e-6, CacheReadInputTokenCost: 0.014e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("deepseek-v4-flash-vision-exp", "deepseek/deepseek-v4-flash-vision-exp", "DeepSeek V4 Flash Vision Exp", "", 1000000, 384000, []string{"text", "image"}, []string{"medium", "high", "max"}, "high", 0, CindyTextPricing{InputCostPerToken: 0.44e-6, OutputCostPerToken: 1.32e-6, CacheReadInputTokenCost: 0.014e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("deepseek-v4-pro", "deepseek/deepseek-v4-pro", "DeepSeek V4 Pro", "DeepSeek V4 Pro reasoning model; only high/max effective (low/medium→high, xhigh→max)", 1000000, 384000, []string{"text"}, []string{"medium", "high", "max"}, "high", 0, CindyTextPricing{InputCostPerToken: 1.32e-6, OutputCostPerToken: 3.96e-6, CacheReadInputTokenCost: 0.044e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("gemini-3.5-flash", "google/gemini-3.5-flash", "Gemini 3.5 Flash", "Google Gemini 3.5 Flash — upgraded Flash with stronger reasoning", 1048576, 65535, []string{"text", "image", "audio", "video", "file"}, []string{"minimal", "low", "medium", "high"}, "medium", 0, CindyTextPricing{InputCostPerToken: 1.5e-6, OutputCostPerToken: 9e-6, InputCostPerTokenPriority: 2.7e-6, OutputCostPerTokenPriority: 16.2e-6, CacheReadInputTokenCost: 0.15e-6, CacheReadInputTokenCostPriority: 0.27e-6, InputCostPerAudioToken: 1e-6}),
	newCindyV4ChatCapability("gemini-3.6-flash", "google/gemini-3.6-flash", "Gemini 3.6 Flash", "Google Gemini 3.6 Flash — frontier intelligence optimized for speed and cost", 1048576, 65536, []string{"text", "image", "audio", "video", "file"}, []string{"minimal", "low", "medium", "high"}, "medium", 0, CindyTextPricing{InputCostPerToken: 1.5e-6, OutputCostPerToken: 7.5e-6, InputCostPerTokenPriority: 2.7e-6, OutputCostPerTokenPriority: 13.5e-6, CacheReadInputTokenCost: 0.15e-6, CacheReadInputTokenCostPriority: 0.27e-6}),
	newCindyV4ChatCapability("gemini-3.7-flash", "google/gemini-3.7-flash", "Gemini 3.7 Flash", "Google Gemini 3.7 Flash — agentic workflows and multimodal reasoning", 1048576, 65536, []string{"text", "image", "audio", "video"}, []string{"low", "medium", "high"}, "medium", 0, CindyTextPricing{InputCostPerToken: 0.75e-6, OutputCostPerToken: 3.75e-6, InputCostPerTokenPriority: 1.35e-6, OutputCostPerTokenPriority: 6.75e-6, CacheReadInputTokenCost: 0.075e-6, CacheReadInputTokenCostPriority: 0.135e-6}),
	newCindyV4ChatCapability("kimi-k3", "moonshotai/kimi-k3", "Kimi K3", "", 1048576, 131072, []string{"text", "image", "video"}, []string{"low", "medium", "high", "max"}, "max", 0, CindyTextPricing{InputCostPerToken: 3e-6, OutputCostPerToken: 15e-6, CacheReadInputTokenCost: 0.3e-6}),
	newCindyV4ChatCapability("gpt-5.6-luna", "openai/gpt-5.6-luna", "GPT-5.6 Luna", "", 1050000, 128000, []string{"text", "image", "file"}, []string{"low", "medium", "high", "xhigh", "max"}, "medium", 0, CindyTextPricing{InputCostPerToken: 0.2e-6, OutputCostPerToken: 1.2e-6, InputCostPerTokenPriority: 2e-6, OutputCostPerTokenPriority: 12e-6, CacheReadInputTokenCost: 0.02e-6, CacheReadInputTokenCostPriority: 0.2e-6, LongContextInputTokenThreshold: 272000, LongContextInputCostPerToken: 2e-6, LongContextOutputCostPerToken: 9e-6, LongContextCacheReadInputTokenCost: 0.2e-6, LongContextInputCostPerTokenPriority: 4e-6, LongContextOutputCostPerTokenPriority: 18e-6, LongContextCacheReadInputTokenCostPriority: 0.4e-6}),
	newCindyV4ChatCapability("gpt-5.6-sol", "openai/gpt-5.6-sol", "GPT-5.6 Sol", "GPT-5.6-Sol for coding tasks", 1050000, 128000, []string{"text", "image", "file"}, []string{"low", "medium", "high", "xhigh", "max"}, "medium", 0, CindyTextPricing{InputCostPerToken: 5e-6, OutputCostPerToken: 30e-6, InputCostPerTokenPriority: 10e-6, OutputCostPerTokenPriority: 60e-6, CacheReadInputTokenCost: 0.5e-6, CacheReadInputTokenCostPriority: 1e-6, LongContextInputTokenThreshold: 272000, LongContextInputCostPerToken: 10e-6, LongContextOutputCostPerToken: 45e-6, LongContextCacheReadInputTokenCost: 1e-6, LongContextInputCostPerTokenPriority: 20e-6, LongContextOutputCostPerTokenPriority: 90e-6, LongContextCacheReadInputTokenCostPriority: 2e-6}),
	newCindyV4ChatCapability("gpt-5.6-terra", "openai/gpt-5.6-terra", "GPT-5.6 Terra", "GPT-5.6-Terra for coding tasks", 1050000, 128000, []string{"text", "image", "file"}, []string{"low", "medium", "high", "xhigh", "max"}, "medium", 0, CindyTextPricing{InputCostPerToken: 2e-6, OutputCostPerToken: 12e-6, InputCostPerTokenPriority: 5e-6, OutputCostPerTokenPriority: 30e-6, CacheReadInputTokenCost: 0.2e-6, CacheReadInputTokenCostPriority: 0.5e-6, LongContextInputTokenThreshold: 272000, LongContextInputCostPerToken: 5e-6, LongContextOutputCostPerToken: 22.5e-6, LongContextCacheReadInputTokenCost: 0.5e-6, LongContextInputCostPerTokenPriority: 10e-6, LongContextOutputCostPerTokenPriority: 45e-6, LongContextCacheReadInputTokenCostPriority: 1e-6}),
	newCindyV4ChatCapability("qwen3.8-max", "qwen/qwen3.8-max", "Qwen3.8 Max", "", 991808, 131072, []string{"text", "image"}, []string{"low", "medium", "high", "xhigh"}, "xhigh", 0, CindyTextPricing{InputCostPerToken: 2e-6, OutputCostPerToken: 6e-6, CacheReadInputTokenCost: 0.25e-6, CacheCreationInputTokenCost: 2.5e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("hy3", "tencent/hy3", "Hy3", "", 262144, 128000, []string{"text"}, []string{"low", "medium", "high"}, "high", 0.9, CindyTextPricing{InputCostPerToken: 0.132e-6, OutputCostPerToken: 0.528e-6, CacheReadInputTokenCost: 0.033e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("grok-4.5", "x-ai/grok-4.5", "Grok 4.5", "", 500000, 500000, []string{"text", "image", "file"}, []string{"low", "medium", "high"}, "high", 0, CindyTextPricing{InputCostPerToken: 2e-6, OutputCostPerToken: 6e-6, CacheReadInputTokenCost: 0.3e-6, LongContextInputTokenThreshold: 200000, LongContextInputCostPerToken: 4e-6, LongContextOutputCostPerToken: 12e-6, LongContextCacheReadInputTokenCost: 0.6e-6}),
	newCindyV4ChatCapability("grok-4.6", "x-ai/grok-4.6", "Grok 4.6", "", 500000, 500000, []string{"text", "image", "file"}, []string{"low", "medium", "high", "xhigh"}, "high", 0, CindyTextPricing{InputCostPerToken: 2e-6, OutputCostPerToken: 6e-6, CacheReadInputTokenCost: 0.5e-6, LongContextInputTokenThreshold: 200000, LongContextInputCostPerToken: 4e-6, LongContextOutputCostPerToken: 12e-6, LongContextCacheReadInputTokenCost: 1e-6}),
	newCindyV4ChatCapability("glm-5.2", "z-ai/glm-5.2", "GLM 5.2", "Zhipu GLM-5.2 agentic coding model; 1M context", 1000000, 131072, []string{"text"}, []string{"minimal", "medium", "high", "max"}, "max", 0.3, CindyTextPricing{InputCostPerToken: 1.4e-6, OutputCostPerToken: 4.4e-6, CacheReadInputTokenCost: 0.26e-6, CacheCreationInputTokenCostPresent: true}),
	newCindyV4ChatCapability("glm-5.3", "z-ai/glm-5.3", "GLM 5.3", "Zhipu GLM-5.3 agentic coding model; 1M context", 1000000, 131072, []string{"text"}, []string{"low", "medium", "high", "max"}, "max", 0.2, CindyTextPricing{InputCostPerToken: 1.4e-6, OutputCostPerToken: 4.4e-6, CacheReadInputTokenCost: 0.26e-6, CacheCreationInputTokenCostPresent: true}),
	{
		PublicID: "gemini-3-pro-image", LiveUpstreamID: "google/gemini-3-pro-image", RegistryID: "google/gemini-3-pro-image", DisplayName: "Gemini 3 Pro Image", Kind: CindyModelKindImage,
		InputModalities: []string{"text", "image"}, OutputModalities: []string{"text", "image"}, VerifiedEndpoints: []CindyEndpoint{CindyEndpointImagesGenerate, CindyEndpointImagesEdit}, ClientSurfaces: []string{CindyClientSurfaceImage},
		MaxInputTokens: 65536, CodexContextWindow: 65536, MaxOutputTokens: 32768, MetadataSourceRevision: CindyModelMetadataSourceRevision, PricingSource: CindyModelMetadataSourceRevision,
		ImagePricing: &CindyImagePricing{InputCostPerToken: 2e-6, OutputCostPerToken: 12e-6, InputCostPerImage: 0.0011, OutputCostPerImage: 0.134, OutputCostPerImageToken: 120e-6},
		Controls:     &CindyCapabilityControls{Generation: &CindyImageRequestControls{Sizes: []string{"1024x1024"}, Qualities: []string{"low"}, MaxOutputCount: 1}, Edit: &CindyImageRequestControls{Sizes: []string{"1024x1024"}, Qualities: []string{"low"}, MaxOutputCount: 1, SupportsReferenceImage: true, SupportsMask: true}}, PublicModel: true,
	},
	{
		PublicID: "gpt-image-2", LiveUpstreamID: "openai/gpt-image-2", RegistryID: "openai/gpt-image-2", DisplayName: "GPT Image 2", Kind: CindyModelKindImage,
		InputModalities: []string{"text", "image", "file"}, OutputModalities: []string{"text", "image"}, VerifiedEndpoints: []CindyEndpoint{CindyEndpointImagesGenerate}, ClientSurfaces: []string{CindyClientSurfaceImage},
		MetadataSourceRevision: CindyModelMetadataSourceRevision, PricingSource: CindyModelMetadataSourceRevision,
		ImagePricing: &CindyImagePricing{InputCostPerToken: 5e-6, OutputCostPerToken: 10e-6, CacheReadInputTokenCost: 1.25e-6, InputCostPerImageToken: 8e-6, OutputCostPerImageToken: 30e-6},
		Controls:     &CindyCapabilityControls{Generation: &CindyImageRequestControls{Sizes: []string{"1024x1024"}, Qualities: []string{"low"}, MaxOutputCount: 1}}, PublicModel: true,
	},
}

func newCindyV4ChatCapability(publicID, liveID, displayName, description string, contextWindow, maxOutputTokens int, inputModalities, efforts []string, defaultEffort string, costDiscount float64, pricing CindyTextPricing) CindyCapability {
	return CindyCapability{
		PublicID: publicID, LiveUpstreamID: liveID, RegistryID: liveID,
		DisplayName: displayName, Description: description, Kind: CindyModelKindText,
		InputModalities: inputModalities, OutputModalities: []string{"text"},
		VerifiedEndpoints:  []CindyEndpoint{CindyEndpointResponses, CindyEndpointMessages},
		ClientSurfaces:     []string{CindyClientSurfaceCodex, CindyClientSurfacePi, CindyClientSurfaceOpenAI, CindyClientSurfaceClaude, CindyClientSurfaceAnthropic},
		AgentWireProtocols: map[string]string{"claude-code": "anthropic-messages", "codex": "openai-responses", "pi": "openai-responses"},
		MaxInputTokens:     contextWindow, CodexContextWindow: contextWindow, MaxOutputTokens: maxOutputTokens,
		ReasoningEfforts: efforts, DefaultReasoningEffort: defaultEffort,
		MetadataSourceRevision: CindyModelMetadataSourceRevision, PricingSource: CindyModelMetadataSourceRevision,
		CostDiscount: costDiscount, TextPricing: &pricing, PublicModel: true,
	}
}
