// Code generated by ent, DO NOT EDIT.

package systemprompttemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldDeletedAt, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldSlug, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldDescription, v))
}

// IsSeed applies equality check predicate on the "is_seed" field. It's identical to IsSeedEQ.
func IsSeed(v bool) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldIsSeed, v))
}

// ManagedSource applies equality check predicate on the "managed_source" field. It's identical to ManagedSourceEQ.
func ManagedSource(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldManagedSource, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotNull(FieldDeletedAt))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldContainsFold(FieldSlug, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldContainsFold(FieldDescription, v))
}

// IsSeedEQ applies the EQ predicate on the "is_seed" field.
func IsSeedEQ(v bool) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldIsSeed, v))
}

// IsSeedNEQ applies the NEQ predicate on the "is_seed" field.
func IsSeedNEQ(v bool) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldIsSeed, v))
}

// ManagedSourceEQ applies the EQ predicate on the "managed_source" field.
func ManagedSourceEQ(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldManagedSource, v))
}

// ManagedSourceNEQ applies the NEQ predicate on the "managed_source" field.
func ManagedSourceNEQ(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldManagedSource, v))
}

// ManagedSourceIn applies the In predicate on the "managed_source" field.
func ManagedSourceIn(vs ...string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldManagedSource, vs...))
}

// ManagedSourceNotIn applies the NotIn predicate on the "managed_source" field.
func ManagedSourceNotIn(vs ...string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldManagedSource, vs...))
}

// ManagedSourceGT applies the GT predicate on the "managed_source" field.
func ManagedSourceGT(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldManagedSource, v))
}

// ManagedSourceGTE applies the GTE predicate on the "managed_source" field.
func ManagedSourceGTE(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldManagedSource, v))
}

// ManagedSourceLT applies the LT predicate on the "managed_source" field.
func ManagedSourceLT(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldManagedSource, v))
}

// ManagedSourceLTE applies the LTE predicate on the "managed_source" field.
func ManagedSourceLTE(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldManagedSource, v))
}

// ManagedSourceContains applies the Contains predicate on the "managed_source" field.
func ManagedSourceContains(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldContains(FieldManagedSource, v))
}

// ManagedSourceHasPrefix applies the HasPrefix predicate on the "managed_source" field.
func ManagedSourceHasPrefix(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldHasPrefix(FieldManagedSource, v))
}

// ManagedSourceHasSuffix applies the HasSuffix predicate on the "managed_source" field.
func ManagedSourceHasSuffix(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldHasSuffix(FieldManagedSource, v))
}

// ManagedSourceIsNil applies the IsNil predicate on the "managed_source" field.
func ManagedSourceIsNil() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIsNull(FieldManagedSource))
}

// ManagedSourceNotNil applies the NotNil predicate on the "managed_source" field.
func ManagedSourceNotNil() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotNull(FieldManagedSource))
}

// ManagedSourceEqualFold applies the EqualFold predicate on the "managed_source" field.
func ManagedSourceEqualFold(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEqualFold(FieldManagedSource, v))
}

// ManagedSourceContainsFold applies the ContainsFold predicate on the "managed_source" field.
func ManagedSourceContainsFold(v string) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldContainsFold(FieldManagedSource, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.FieldNotNull(FieldUpdatedBy))
}

// HasVersions applies the HasEdge predicate on the "versions" edge.
func HasVersions() predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionsWith applies the HasEdge predicate on the "versions" edge with a given conditions (other predicates).
func HasVersionsWith(preds ...predicate.SystemPromptTemplateVersion) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(func(s *sql.Selector) {
		step := newVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SystemPromptTemplate) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SystemPromptTemplate) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SystemPromptTemplate) predicate.SystemPromptTemplate {
	return predicate.SystemPromptTemplate(sql.NotPredicates(p))
}
